<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Series extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('series')->insert([
            ['nombre_serie' => 'ACCIONES CONSTITUCIONALES', 'codigo_serie' => 1, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ACTAS', 'codigo_serie' => 2, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ACUERDOS ', 'codigo_serie' => 3, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ADJUDICACION BIENES DECOMISADOS', 'codigo_serie' => 4, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ADMINISTRACION CAPELLANIA FF.MM', 'codigo_serie' => 5, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ADMINISTRACION DEL FONDO DE DEFENSA NACIONAL', 'codigo_serie' => 6, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'AGENDAS', 'codigo_serie' => 64, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'APRECIACIONES', 'codigo_serie' => 72, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'BALANCE ', 'codigo_serie' => 7, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'BANCOS DE PROYECTOS ', 'codigo_serie' => 8, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'BIENES RAICES ', 'codigo_serie' => 9, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'BITACORA ', 'codigo_serie' => 67, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'BOLETINES ', 'codigo_serie' => 10, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CAJA MENOR ', 'codigo_serie' => 11, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CAMPAÑAS', 'codigo_serie' => 57, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CARTOGRAFÍA ', 'codigo_serie' => 58, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CERTIFICADOS ', 'codigo_serie' => 12, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CIERRE ALMACEN TERMINO VIGENCIA', 'codigo_serie' => 68, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CIRCULARES             ', 'codigo_serie' => 13, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'COMISIONES', 'codigo_serie' => 59, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'COMPILACION NORMATIVA', 'codigo_serie' => 14, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CONCEPTOS', 'codigo_serie' => 15, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CONCURSOS', 'codigo_serie' => 16, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CONTRATOS ', 'codigo_serie' => 17, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CONTRAVENCIONES', 'codigo_serie' => 61, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CONVENIOS', 'codigo_serie' => 60, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CUENTAS CORRIENTES', 'codigo_serie' => 18, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CUENTAS FISCALES ', 'codigo_serie' => 19, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'CURSOS', 'codigo_serie' => 62, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DECLARACIONES TRIBUTARIAS ', 'codigo_serie' => 20, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DECRETOS ', 'codigo_serie' => 21, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DERECHOS DE PETICIÓN ', 'codigo_serie' => 22, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DENUNCIAS', 'codigo_serie' => 63, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DICTÁMENES', 'codigo_serie' => 76, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DIRECTIVAS', 'codigo_serie' => 23, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DISPOSICIONES MILITARES', 'codigo_serie' => 52, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'DOCTRINAS', 'codigo_serie' => 39, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ENCUESTAS', 'codigo_serie' => 55, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ENSAYOS', 'codigo_serie' => 77, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ESTADISTICAS', 'codigo_serie' => 56, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ESTUDIOS ', 'codigo_serie' => 24, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'EXPEDIENTES', 'codigo_serie' => 25, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'GASTOS GENERALES ', 'codigo_serie' => 26, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'HISTORIAS CLINICAS', 'codigo_serie' => 78, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'HISTORIAS LABORALES', 'codigo_serie' => 27, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'IMAGEN CORPORATIVA ', 'codigo_serie' => 28, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'INFORMES', 'codigo_serie' => 29, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'INSTRUCTIVOS', 'codigo_serie' => 70, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'INVENTARIOS ', 'codigo_serie' => 30, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'INVERSIONES FINANCIERAS', 'codigo_serie' => 66, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'INVESTIGACIONES', 'codigo_serie' => 73, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'KARDEX', 'codigo_serie' => 74, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'LIBROS ', 'codigo_serie' => 31, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'MANIFIESTO DE SALTO', 'codigo_serie' => 79, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'MANTENIMIENTO', 'codigo_serie' => 32, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'MANUALES ', 'codigo_serie' => 33, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'METODOLOGIAS Y GUIAS ', 'codigo_serie' => 34, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'METEOROLOGÍA', 'codigo_serie' => 35, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'MODELO ESTANDAR DE CONTROL INTERNO', 'codigo_serie' => 80, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'MONITOREOS', 'codigo_serie' => 65, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'NORMAS', 'codigo_serie' => 36, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'NÓMINAS ', 'codigo_serie' => 37, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'OPERACIONES', 'codigo_serie' => 81, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'ORDENES', 'codigo_serie' => 38, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PAGOS PARAFISCALES', 'codigo_serie' => 82, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PLANES ', 'codigo_serie' => 40, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PLANILLAS', 'codigo_serie' => 53, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PLANOS', 'codigo_serie' => 83, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'POLÍTICA', 'codigo_serie' => 84, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PONENCIAS', 'codigo_serie' => 85, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PROCESOS ', 'codigo_serie' => 41, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PROGRAMAS', 'codigo_serie' => 86, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PRONTUARIOS', 'codigo_serie' => 87, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PROPOSICIONES', 'codigo_serie' => 88, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PROTOCOLO MILITAR OFICIAL ', 'codigo_serie' => 42, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PROYECTOS ', 'codigo_serie' => 43, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'PUBLICACIONES', 'codigo_serie' => 54, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'QUEJAS Y RECLAMOS ', 'codigo_serie' => 44, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'REGISTRO DE PROVEEDORES', 'codigo_serie' => 45, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'REGLAMENTOS', 'codigo_serie' => 89, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'REPORTES', 'codigo_serie' => 90, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'RESERVAS', 'codigo_serie' => 91, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'RESOLUCIONES ', 'codigo_serie' => 46, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'SEGURIDAD MILITAR', 'codigo_serie' => 92, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'SISTEMAS DE INFORMACION', 'codigo_serie' => 47, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'TABLAS DE ORGANIZACIÓN Y EQUIPO ( TOE )', 'codigo_serie' => 69, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'TABLAS DE RETENCIÓN DOCUMENTAL ', 'codigo_serie' => 48, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'TITULOS VALORES ', 'codigo_serie' => 49, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'TRANSFERENCIAS ', 'codigo_serie' => 50, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'TRATADOS ', 'codigo_serie' => 51, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],
            ['nombre_serie' => 'VETERINARIA', 'codigo_serie' => 71, 'anio_inicio_serie' => 2007, 'anio_fin_serie' => 2012, 'id_estado' => 1],



            /*************** LISTADO SERIES ACTUALES ***************/
            ['nombre_serie' => 'ACCIONES CONSTITUCIONALES', 'codigo_serie' => 1, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ACTAS', 'codigo_serie' => 2, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ACUERDOS', 'codigo_serie' => 3, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ADMINISTRACION CAPELLANIAS', 'codigo_serie' => 5, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ADMINISTRACIÓN DEL FONDO DE DEFENSA NACIONAL', 'codigo_serie' => 6, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'BANCOS DE PROYECTOS', 'codigo_serie' => 8, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'BIENES RAICES', 'codigo_serie' => 9, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'BOLETINES', 'codigo_serie' => 10, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CAJA MENOR', 'codigo_serie' => 11, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CERTIFICADOS', 'codigo_serie' => 12, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CIRCULARES', 'codigo_serie' => 13, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CONCEPTOS', 'codigo_serie' => 15, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CONCURSOS', 'codigo_serie' => 16, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CONTRATOS', 'codigo_serie' => 17, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CUENTAS CORRIENTES', 'codigo_serie' => 18, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CUENTAS FISCALES', 'codigo_serie' => 19, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'DECLARACIONES TRIBUTARIAS', 'codigo_serie' => 20, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'DECRETOS', 'codigo_serie' => 21, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'DIRECTIVAS', 'codigo_serie' => 23, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ESTUDIOS', 'codigo_serie' => 24, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'EXPEDIENTES', 'codigo_serie' => 25, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'HISTORIAS', 'codigo_serie' => 27, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'IMAGEN INSTITUCIONAL', 'codigo_serie' => 28, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'INFORMES', 'codigo_serie' => 29, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'INVENTARIOS', 'codigo_serie' => 30, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'LIBROS', 'codigo_serie' => 31, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'MANUALES', 'codigo_serie' => 33, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'METEOROLOGÍA', 'codigo_serie' => 35, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'NORMAS TECNICAS', 'codigo_serie' => 36, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'NÓMINAS', 'codigo_serie' => 37, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ORDENES', 'codigo_serie' => 38, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PLANES', 'codigo_serie' => 40, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PROCESOS', 'codigo_serie' => 41, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PROTOCOLO OFICIAL', 'codigo_serie' => 42, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PROYECTOS', 'codigo_serie' => 43, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'RESOLUCIONES', 'codigo_serie' => 46, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'SISTEMAS DE INFORMACION', 'codigo_serie' => 47, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'TABLAS DE RETENCIÓN DOCUMENTAL', 'codigo_serie' => 48, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'TITULOS VALORES', 'codigo_serie' => 49, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'TRANSFERENCIAS', 'codigo_serie' => 50, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'DISPOSICIONES', 'codigo_serie' => 52, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PLANILLAS', 'codigo_serie' => 53, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PUBLICACIONES', 'codigo_serie' => 54, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ESTADISTICAS', 'codigo_serie' => 56, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CAMPAÑAS', 'codigo_serie' => 57, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CARTOGRAFÍA', 'codigo_serie' => 58, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'COMISIONES', 'codigo_serie' => 59, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CONVENIOS', 'codigo_serie' => 60, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CONTRAVENCIONES', 'codigo_serie' => 61, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'AGENDAS', 'codigo_serie' => 64, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'MONITOREOS', 'codigo_serie' => 65, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'BITACORA', 'codigo_serie' => 67, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'INSTRUCTIVOS', 'codigo_serie' => 70, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'DICTAMENES PERICIALES', 'codigo_serie' => 76, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'MANIFIESTO DE SALTO', 'codigo_serie' => 79, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'OPERACIONES', 'codigo_serie' => 81, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'POLÍTICAS', 'codigo_serie' => 84, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PONENCIAS', 'codigo_serie' => 85, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'PROGRAMAS', 'codigo_serie' => 86, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'MECANISMOS DE COOPERACIÓN', 'codigo_serie' => 93, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'ESTADOS PROPIEDAD PLANTA Y EQUIPO', 'codigo_serie' => 94, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'SISTEMAS DE GESTIÓN', 'codigo_serie' => 95, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'CONTROL PRESUPUESTAL', 'codigo_serie' => 96, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],
            ['nombre_serie' => 'TALENTO HUMANO', 'codigo_serie' => 586, 'anio_inicio_serie' => 2013, 'anio_fin_serie' => 2028, 'id_estado' => 1],



        ]);
    }
}
