<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Subseries extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('subseries')->insert([




            ['codigo_subserie' => '1.1', 'nombre_subserie' => 'Acción de Cumplimiento', 'id_serie' => 1],
            ['codigo_subserie' => '1.2', 'nombre_subserie' => 'Acción de Nulidad y Restablecimiento del Derecho', 'id_serie' => 1],
            ['codigo_subserie' => '1.3', 'nombre_subserie' => 'Acción de Reparación', 'id_serie' => 1],
            ['codigo_subserie' => '1.4', 'nombre_subserie' => 'Acción de Reparación Directa', 'id_serie' => 1],
            ['codigo_subserie' => '1.5', 'nombre_subserie' => 'Acción de Tutela', 'id_serie' => 1],
            ['codigo_subserie' => '1.6', 'nombre_subserie' => 'Acción Popular', 'id_serie' => 1],
            ['codigo_subserie' => '1.7', 'nombre_subserie' => 'Habeas Corpus', 'id_serie' => 1],
            ['codigo_subserie' => '1.8', 'nombre_subserie' => 'Habeas Data', 'id_serie' => 1],
            ['codigo_subserie' => '1.9', 'nombre_subserie' => 'Requerimientos de Justicia', 'id_serie' => 1],


            ['codigo_subserie' => '2.1', 'nombre_subserie' => 'Actas Asignacion Material', 'id_serie' => 2],
            ['codigo_subserie' => '2.2', 'nombre_subserie' => 'Actas Asignacón Vehículo', 'id_serie' => 2],
            ['codigo_subserie' => '2.3', 'nombre_subserie' => 'Actas Comision de Personal', 'id_serie' => 2],
            ['codigo_subserie' => '2.4', 'nombre_subserie' => 'Actas Comité Bienestar Social', 'id_serie' => 2],
            ['codigo_subserie' => '2.5', 'nombre_subserie' => 'Actas Cornité Técnico de Archivo', 'id_serie' => 2],
            ['codigo_subserie' => '2.6', 'nombre_subserie' => 'Actas Comité de Capacitacion', 'id_serie' => 2],
            ['codigo_subserie' => '2.7', 'nombre_subserie' => 'Actas Comité de Informatica', 'id_serie' => 2],
            ['codigo_subserie' => '2.8', 'nombre_subserie' => 'Actas Comite Conciliacion', 'id_serie' => 2],
            ['codigo_subserie' => '2.9', 'nombre_subserie' => 'Actas Comité Directivo de Normalizacion', 'id_serie' => 2],
            ['codigo_subserie' => '2.10', 'nombre_subserie' => 'Comité Paritario de Salud Ocupacional Actas', 'id_serie' => 2],
            ['codigo_subserie' => '2.11', 'nombre_subserie' => 'Actas Comité Sistema Coordinación Control Interno', 'id_serie' => 2],
            ['codigo_subserie' => '2.12', 'nombre_subserie' => 'Actas Consejo Asesor de Asuntos Economicos', 'id_serie' => 2],
            ['codigo_subserie' => '2.13', 'nombre_subserie' => 'Actas Consejo Asesor Consultores', 'id_serie' => 2],
            ['codigo_subserie' => '2.14', 'nombre_subserie' => 'Actas Consejo Asesor de Gobierno', 'id_serie' => 2],
            ['codigo_subserie' => '2.15', 'nombre_subserie' => 'Actas Consejo Asesor Soluciones Equitativas', 'id_serie' => 2],
            ['codigo_subserie' => '2.16', 'nombre_subserie' => 'Actas Consejo Asesor Pastoral', 'id_serie' => 2],
            ['codigo_subserie' => '2.17', 'nombre_subserie' => 'Actas Consejo Asesor Presbiterial', 'id_serie' => 2],
            ['codigo_subserie' => '2.18', 'nombre_subserie' => 'Actas Consejo Superior de Salud de las FF.MM.', 'id_serie' => 2],
            ['codigo_subserie' => '2.19', 'nombre_subserie' => 'Actas de Alerta Tempranas', 'id_serie' => 2],
            ['codigo_subserie' => '2.20', 'nombre_subserie' => 'Actas de Acuerdo de Comandantes', 'id_serie' => 2],
            ['codigo_subserie' => '2.21', 'nombre_subserie' => 'Actas de Entrega de Dependencias', 'id_serie' => 2],
            ['codigo_subserie' => '2.22', 'nombre_subserie' => 'Actas de Posesión', 'id_serie' => 2],
            ['codigo_subserie' => '2.23', 'nombre_subserie' => 'Actas de Reintegro', 'id_serie' => 2],
            ['codigo_subserie' => '2.24', 'nombre_subserie' => 'Actas de Reuniones de Capellanes', 'id_serie' => 2],
            ['codigo_subserie' => '2.25', 'nombre_subserie' => 'Actas de Reuniones de Trabajo', 'id_serie' => 2],
            ['codigo_subserie' => '2.26', 'nombre_subserie' => 'Actas de subcomite local Coordinación Control Inter', 'id_serie' => 2],
            ['codigo_subserie' => '2.27', 'nombre_subserie' => 'Actas de Traspaso', 'id_serie' => 2],
            ['codigo_subserie' => '2.28', 'nombre_subserie' => 'Actas de Apoyos Educativos', 'id_serie' => 2],
            ['codigo_subserie' => '2.29', 'nombre_subserie' => 'Actas de Asignación de Vivienda Fiscal', 'id_serie' => 2],
            ['codigo_subserie' => '2.30', 'nombre_subserie' => 'Actas de Baja de Vehiculos', 'id_serie' => 2],
            ['codigo_subserie' => '2.31', 'nombre_subserie' => 'Actas de Bajas de Material', 'id_serie' => 2],
            ['codigo_subserie' => '2.32', 'nombre_subserie' => 'Actas de Cortes Marciales', 'id_serie' => 2],
            ['codigo_subserie' => '2.33', 'nombre_subserie' => 'Actas de Junta de Compras', 'id_serie' => 2],
            ['codigo_subserie' => '2.34', 'nombre_subserie' => 'Actas de Buen Trato', 'id_serie' => 2],
            ['codigo_subserie' => '2.35', 'nombre_subserie' => 'Actas de Capacitación', 'id_serie' => 2],
            ['codigo_subserie' => '2.36', 'nombre_subserie' => 'Actas de Combustibles', 'id_serie' => 2],
            ['codigo_subserie' => '2.37', 'nombre_subserie' => 'Actas de Comisión Carrera Administrativa', 'id_serie' => 2],
            ['codigo_subserie' => '2.38', 'nombre_subserie' => 'Actas Comité Salud Sanidad Militar', 'id_serie' => 2],
            ['codigo_subserie' => '2.39', 'nombre_subserie' => 'Actas Recepción de Material', 'id_serie' => 2],
            ['codigo_subserie' => '2.40', 'nombre_subserie' => 'Actas de Revista de Material', 'id_serie' => 2],
            ['codigo_subserie' => '2.41', 'nombre_subserie' => 'Actas Destrucción Cedulas Militares', 'id_serie' => 2],
            ['codigo_subserie' => '2.42', 'nombre_subserie' => 'Actas Entrega Elementos', 'id_serie' => 2],
            ['codigo_subserie' => '2.43', 'nombre_subserie' => 'Actas de Reunión de Estado Mayor', 'id_serie' => 2],
            ['codigo_subserie' => '2.44', 'nombre_subserie' => 'Actas Revisión Nómina', 'id_serie' => 2],
            ['codigo_subserie' => '2.45', 'nombre_subserie' => 'Actas de Revista Dependencias', 'id_serie' => 2],
            ['codigo_subserie' => '2.46', 'nombre_subserie' => 'Actas Consejo Directivo', 'id_serie' => 2],
            ['codigo_subserie' => '2.47', 'nombre_subserie' => 'Actas Donaciones', 'id_serie' => 2],
            ['codigo_subserie' => '2.48', 'nombre_subserie' => 'Actas Control de Calidad', 'id_serie' => 2],
            ['codigo_subserie' => '2.49', 'nombre_subserie' => 'Actas Cuerpo Colegiado', 'id_serie' => 2],
            ['codigo_subserie' => '2.50', 'nombre_subserie' => 'Actas Actualización de cargos', 'id_serie' => 2],
            ['codigo_subserie' => '2.51', 'nombre_subserie' => 'Comité Análisis Operacional Actas', 'id_serie' => 2],
            ['codigo_subserie' => '2.52', 'nombre_subserie' => 'Actas Junta de Contra inteligencia', 'id_serie' => 2],
            ['codigo_subserie' => '2.53', 'nombre_subserie' => 'Actas Junta de inteligencia', 'id_serie' => 2],
            ['codigo_subserie' => '2.54', 'nombre_subserie' => 'Actas Arqueo de Caja y Chequera', 'id_serie' => 2],
            ['codigo_subserie' => '2.55', 'nombre_subserie' => 'Actas Comité Banco de Sangre', 'id_serie' => 2],
            ['codigo_subserie' => '2.56', 'nombre_subserie' => 'Actas Comité CODA', 'id_serie' => 2],
            ['codigo_subserie' => '2.57', 'nombre_subserie' => 'Actas Comité de Control Interno', 'id_serie' => 2],
            ['codigo_subserie' => '2.58', 'nombre_subserie' => 'Actas Comité de Ética y Transparencia', 'id_serie' => 2],
            ['codigo_subserie' => '2.59', 'nombre_subserie' => 'Actas Comité de Historias Clinicas', 'id_serie' => 2],
            ['codigo_subserie' => '2.60', 'nombre_subserie' => 'Actas Comité de Infecciones', 'id_serie' => 2],
            ['codigo_subserie' => '2.61', 'nombre_subserie' => 'Actas Comité de Medicamentos', 'id_serie' => 2],
            ['codigo_subserie' => '2.62', 'nombre_subserie' => 'Actas Comité de Oficiales', 'id_serie' => 2],
            ['codigo_subserie' => '2.63', 'nombre_subserie' => 'Actas Comité de Operativos', 'id_serie' => 2],
            ['codigo_subserie' => '2.64', 'nombre_subserie' => 'Actas Cornité de Promoción y Prevención', 'id_serie' => 2],
            ['codigo_subserie' => '2.65', 'nombre_subserie' => 'Actas Comité de Vacunación', 'id_serie' => 2],
            ['codigo_subserie' => '2.66', 'nombre_subserie' => 'Actas Comité del Cuerpo Superior de Educación Naval', 'id_serie' => 2],
            ['codigo_subserie' => '2.67', 'nombre_subserie' => 'Actas Comité Derechos Humanos', 'id_serie' => 2],
            ['codigo_subserie' => '2.68', 'nombre_subserie' => 'Actas Cornité Medios de Comunicación', 'id_serie' => 2],
            ['codigo_subserie' => '2.69', 'nombre_subserie' => 'Actas Comité Sostenibilidad del Sistema de Contabilidad Pública.', 'id_serie' => 2],
            ['codigo_subserie' => '2.70', 'nombre_subserie' => 'Actas Compromiso Armas', 'id_serie' => 2],
            ['codigo_subserie' => '2.71', 'nombre_subserie' => 'Actas Compromiso Recursos Tecnológicos', 'id_serie' => 2],
            ['codigo_subserie' => '2.72', 'nombre_subserie' => 'Actas Conciliación Saldos Cuentas Holding Account', 'id_serie' => 2],
            ['codigo_subserie' => '2.73', 'nombre_subserie' => 'Actas Consejo Académico', 'id_serie' => 2],
            ['codigo_subserie' => '2.74', 'nombre_subserie' => 'Actas Consejo de Disciplina', 'id_serie' => 2],
            ['codigo_subserie' => '2.75', 'nombre_subserie' => 'Actas Consejo de Seguridad', 'id_serie' => 2],
            ['codigo_subserie' => '2.77', 'nombre_subserie' => 'Actas de Comité de Estudios para Ascensos.', 'id_serie' => 2],
            ['codigo_subserie' => '2.78', 'nombre_subserie' => 'Actas de Compromiso', 'id_serie' => 2],
            ['codigo_subserie' => '2.79', 'nombre_subserie' => 'Actas de Cortes Marciales', 'id_serie' => 2],
            ['codigo_subserie' => '2.80', 'nombre_subserie' => 'Actas de Ejecución y Apropiación PAC', 'id_serie' => 2],
            ['codigo_subserie' => '2.81', 'nombre_subserie' => 'Actas de Eliminación Documental', 'id_serie' => 2],
            ['codigo_subserie' => '2.82', 'nombre_subserie' => 'Actas de Entrega de Armamento', 'id_serie' => 2],
            ['codigo_subserie' => '2.83', 'nombre_subserie' => 'Actas de Entrega de Cargo', 'id_serie' => 2],
            ['codigo_subserie' => '2.84', 'nombre_subserie' => 'Actas de Entrega de Material', 'id_serie' => 2],
            ['codigo_subserie' => '2.85', 'nombre_subserie' => 'Actas de Entrega de Unidad', 'id_serie' => 2],
            ['codigo_subserie' => '2.86', 'nombre_subserie' => 'Actas de Evaluación de Procesos', 'id_serie' => 2],
            ['codigo_subserie' => '2.87', 'nombre_subserie' => 'Actas de Inasistencia al Servicio', 'id_serie' => 2],
            ['codigo_subserie' => '2.88', 'nombre_subserie' => 'Actas de Informe de Gestión.', 'id_serie' => 2],
            ['codigo_subserie' => '2.89', 'nombre_subserie' => 'Actas de Inicio y Término de Curso', 'id_serie' => 2],
            ['codigo_subserie' => '2.90', 'nombre_subserie' => 'Actas de Insdtrucción Seguridad Centro de Reclusión', 'id_serie' => 2],
            ['codigo_subserie' => '2.91', 'nombre_subserie' => 'Actas de Inspección Judicial', 'id_serie' => 2],
            ['codigo_subserie' => '2.92', 'nombre_subserie' => 'Actas de Instrucción a la Tropa', 'id_serie' => 2],
            ['codigo_subserie' => '2.93', 'nombre_subserie' => 'Actas de Instrucción Contable', 'id_serie' => 2],
            ['codigo_subserie' => '2.94', 'nombre_subserie' => 'Actas de Investigación y Desarrollo', 'id_serie' => 2],
            ['codigo_subserie' => '2.95', 'nombre_subserie' => 'Actas de Junta Médica', 'id_serie' => 2],
            ['codigo_subserie' => '2.96', 'nombre_subserie' => 'Actas de Reserva', 'id_serie' => 2],
            ['codigo_subserie' => '2.97', 'nombre_subserie' => 'Actas de Seguimiento Administración de Recursos Fisicos', 'id_serie' => 2],
            ['codigo_subserie' => '2.98', 'nombre_subserie' => 'Actas de Seguridad', 'id_serie' => 2],
            ['codigo_subserie' => '2.99', 'nombre_subserie' => 'Actas Destrucción Formularios DCCA', 'id_serie' => 2],
            ['codigo_subserie' => '2.100', 'nombre_subserie' => 'Actas Destruccion Material Decomisado', 'id_serie' => 2],
            ['codigo_subserie' => '2.101', 'nombre_subserie' => 'Actas Destrucción Salvocunductos', 'id_serie' => 2],
            ['codigo_subserie' => '2.102', 'nombre_subserie' => 'Actas Fundicion Material Decomisado', 'id_serie' => 2],
            ['codigo_subserie' => '2.103', 'nombre_subserie' => 'Actas Junta Asesora', 'id_serie' => 2],
            ['codigo_subserie' => '2.104', 'nombre_subserie' => 'Actas Junta de Evaluación y Clasificación', 'id_serie' => 2],
            ['codigo_subserie' => '2.105', 'nombre_subserie' => 'Actas Junta Directiva', 'id_serie' => 2],
            ['codigo_subserie' => '2.106', 'nombre_subserie' => 'Actas Revistas armas decomisadas', 'id_serie' => 2],
            ['codigo_subserie' => '2.107', 'nombre_subserie' => 'Actas Análisis Encuestas y Sugerencias', 'id_serie' => 2],
            ['codigo_subserie' => '2.108', 'nombre_subserie' => 'Comité Adquisiciones ACOFA Actas', 'id_serie' => 2],
            ['codigo_subserie' => '2.109', 'nombre_subserie' => 'Actas de Adjudicación Alojamiento Militar', 'id_serie' => 2],
            ['codigo_subserie' => '2.110', 'nombre_subserie' => 'Actas de Comité Análisis Estratégico (RAE)', 'id_serie' => 2],
            ['codigo_subserie' => '2.111', 'nombre_subserie' => 'Actas de Consejo Aeronautico', 'id_serie' => 2],
            ['codigo_subserie' => '2.112', 'nombre_subserie' => 'Actas de Consejo Editorial', 'id_serie' => 2],

            ['codigo_subserie' => '3.1', 'nombre_subserie' => 'Modificaciones presupuestales', 'id_serie' => 3],
            ['codigo_subserie' => '3.2', 'nombre_subserie' => 'Reservas Presupuestales', 'id_serie' => 3],
            ['codigo_subserie' => '3.3', 'nombre_subserie' => 'Traslados Presupuestales', 'id_serie' => 3],
            ['codigo_subserie' => '3.4', 'nombre_subserie' => 'Cooperación Internacional', 'id_serie' => 3],
            ['codigo_subserie' => '3.5', 'nombre_subserie' => 'Cooperación Nacional', 'id_serie' => 3],

            ['codigo_subserie' => '7.1', 'nombre_subserie' => 'Balance Diario', 'id_serie' => 7],
            ['codigo_subserie' => '7.2', 'nombre_subserie' => 'Balance General', 'id_serie' => 7],
            ['codigo_subserie' => '7.3', 'nombre_subserie' => 'Balance Plan Colombia', 'id_serie' => 7],

            ['codigo_subserie' => '8.1', 'nombre_subserie' => 'Proyectos de Inversón Nacional', 'id_serie' => 8],
            ['codigo_subserie' => '8.2', 'nombre_subserie' => 'Anteproyecto', 'id_serie' => 8],
            ['codigo_subserie' => '8.3', 'nombre_subserie' => 'Marco de Gasto Mediano Plazo (MGMP)', 'id_serie' => 8],
            ['codigo_subserie' => '8.4', 'nombre_subserie' => 'Proyectos de Funcionamiento', 'id_serie' => 8],

            ['codigo_subserie' => '10.1', 'nombre_subserie' => 'Boletines Diarios', 'id_serie' => 10],
            ['codigo_subserie' => '10.2', 'nombre_subserie' => 'Boletines Informativos', 'id_serie' => 10],
            ['codigo_subserie' => '10.3', 'nombre_subserie' => 'Boletines Jurídicos', 'id_serie' => 10],
            ['codigo_subserie' => '10.4', 'nombre_subserie' => 'Boletines Técnicos', 'id_serie' => 10],
            ['codigo_subserie' => '10.5', 'nombre_subserie' => 'Boletines de Inteligencia Informatica', 'id_serie' => 10],
            ['codigo_subserie' => '10.6', 'nombre_subserie' => 'Boletines Económicos', 'id_serie' => 10],
            ['codigo_subserie' => '10.7', 'nombre_subserie' => 'Boletines Politico Sociales', 'id_serie' => 10],
            ['codigo_subserie' => '10.8', 'nombre_subserie' => 'Boletines de Contratación', 'id_serie' => 10],
            ['codigo_subserie' => '10.9', 'nombre_subserie' => 'Boletines de Inteligencia', 'id_serie' => 10],
            ['codigo_subserie' => '10.10', 'nombre_subserie' => 'Boletines de Prensa', 'id_serie' => 10],
            ['codigo_subserie' => '10.11', 'nombre_subserie' => 'Boletines de Resultado de Puentes', 'id_serie' => 10],
            ['codigo_subserie' => '10.12', 'nombre_subserie' => 'Boletines Operacionales', 'id_serie' => 10],
            ['codigo_subserie' => '10.13', 'nombre_subserie' => 'Boletines Semanales', 'id_serie' => 10],
            ['codigo_subserie' => '10.14', 'nombre_subserie' => 'Boletines Tácticos', 'id_serie' => 10],

            ['codigo_subserie' => '12.1', 'nombre_subserie' => 'Certificado de Disponibilidad Presupuestal', 'id_serie' => 12],
            ['codigo_subserie' => '12.2', 'nombre_subserie' => 'Certificado de Registro Presupuestal', 'id_serie' => 12],
            ['codigo_subserie' => '12.3', 'nombre_subserie' => 'Certificado de Clasificación', 'id_serie' => 12],
            ['codigo_subserie' => '12.4', 'nombre_subserie' => 'Certificado de Aeronavegabilidad', 'id_serie' => 12],
            ['codigo_subserie' => '12.5', 'nombre_subserie' => 'Certificado de Aptitud Sicofísica', 'id_serie' => 12],
            ['codigo_subserie' => '12.6', 'nombre_subserie' => 'Certificado de Armas antes 1900', 'id_serie' => 12],
            ['codigo_subserie' => '12.7', 'nombre_subserie' => 'Certificado de Armas inutilizadas', 'id_serie' => 12],
            ['codigo_subserie' => '12.8', 'nombre_subserie' => 'Certificado de Bono Pensional', 'id_serie' => 12],
            ['codigo_subserie' => '12.9', 'nombre_subserie' => 'Certificado de Cancelación Matrícula', 'id_serie' => 12],
            ['codigo_subserie' => '12.10', 'nombre_subserie' => 'Certificado de Contrato', 'id_serie' => 12],
            ['codigo_subserie' => '12.11', 'nombre_subserie' => 'Certificado de Derechos Humanos', 'id_serie' => 12],
            ['codigo_subserie' => '12.12', 'nombre_subserie' => 'Certificado de Prestación de Servicios', 'id_serie' => 12],

            ['codigo_subserie' => '13.1', 'nombre_subserie' => 'Circulares de Prevención', 'id_serie' => 13],
            ['codigo_subserie' => '13.2', 'nombre_subserie' => 'Circulares Informativas', 'id_serie' => 13],
            ['codigo_subserie' => '13.3', 'nombre_subserie' => 'Circulares Financieras', 'id_serie' => 13],
            ['codigo_subserie' => '13.4', 'nombre_subserie' => 'Circulares Reglamentarias', 'id_serie' => 13],

            ['codigo_subserie' => '15.1', 'nombre_subserie' => 'Concepto Juridico', 'id_serie' => 15],
            ['codigo_subserie' => '15.2', 'nombre_subserie' => 'Concepto Técnico', 'id_serie' => 15],
            ['codigo_subserie' => '15.3', 'nombre_subserie' => 'Concepto Personal Militar y Civil', 'id_serie' => 15],
            ['codigo_subserie' => '15.4', 'nombre_subserie' => 'Concepto informativo por lesiones', 'id_serie' => 15],

            ['codigo_subserie' => '15.5', 'nombre_subserie' => 'Concepto lecciones aprendidas', 'id_serie' => 15],
            ['codigo_subserie' => '15.6', 'nombre_subserie' => 'Concepto Administrativo', 'id_serie' => 15],
            ['codigo_subserie' => '15.7', 'nombre_subserie' => 'Concepto Agendas, Juntas y Concejos Directivos', 'id_serie' => 15],
            ['codigo_subserie' => '15.8', 'nombre_subserie' => 'Concepto Agregadurias Militares', 'id_serie' => 15],
            ['codigo_subserie' => '15.9', 'nombre_subserie' => 'Concepto Asistencial', 'id_serie' => 15],
            ['codigo_subserie' => '15.10', 'nombre_subserie' => 'Concepto Contable', 'id_serie' => 15],
            ['codigo_subserie' => '15.11', 'nombre_subserie' => 'Concepto de Auditoria', 'id_serie' => 15],
            ['codigo_subserie' => '15.12', 'nombre_subserie' => 'Concepto de Defensa Institucional', 'id_serie' => 15],
            ['codigo_subserie' => '15.13', 'nombre_subserie' => 'Concepto de Derechos Humanos', 'id_serie' => 15],
            ['codigo_subserie' => '15.14', 'nombre_subserie' => 'Concepto de Inteligencia y Contrainteligencia', 'id_serie' => 15],
            ['codigo_subserie' => '15.15', 'nombre_subserie' => 'Concepto de Planeación', 'id_serie' => 15],
            ['codigo_subserie' => '15.16', 'nombre_subserie' => 'Concepto de Política Exterior', 'id_serie' => 15],
            ['codigo_subserie' => '15.17', 'nombre_subserie' => 'Concepto Financiero', 'id_serie' => 15],
            ['codigo_subserie' => '15.18', 'nombre_subserie' => 'Concepto Prestación de Servicio de Salud', 'id_serie' => 15],
            ['codigo_subserie' => '15.19', 'nombre_subserie' => 'Concepto Presupuestal', 'id_serie' => 15],

            ['codigo_subserie' => '16.1', 'nombre_subserie' => 'CONCURSOS', 'id_serie' => 16],

            ['codigo_subserie' => '17.1', 'nombre_subserie' => 'Contrato de Arrendamiento', 'id_serie' => 17],
            ['codigo_subserie' => '17.2', 'nombre_subserie' => 'Contrato de Bienes o Servicios', 'id_serie' => 17],
            ['codigo_subserie' => '17.3', 'nombre_subserie' => 'Contrato de Compraventa', 'id_serie' => 17],
            ['codigo_subserie' => '17.4', 'nombre_subserie' => 'Contrato de Enajenación y Tenencia', 'id_serie' => 17],
            ['codigo_subserie' => '17.5', 'nombre_subserie' => 'Contrato de Prestación de Servicios', 'id_serie' => 17],
            ['codigo_subserie' => '17.6', 'nombre_subserie' => 'Contrato de Comodato', 'id_serie' => 17],
            ['codigo_subserie' => '17.7', 'nombre_subserie' => 'Contrato Interadministrativo', 'id_serie' => 17],
            ['codigo_subserie' => '17.8', 'nombre_subserie' => 'Contrato trabajador Oficial', 'id_serie' => 17],
            ['codigo_subserie' => '17.9', 'nombre_subserie' => 'Contrato de Obra', 'id_serie' => 17],

            ['codigo_subserie' => '18.1', 'nombre_subserie' => 'Acreedores Varios', 'id_serie' => 18],
            ['codigo_subserie' => '18.2', 'nombre_subserie' => 'Dineros sujetos a devolución', 'id_serie' => 18],
            ['codigo_subserie' => '18.3', 'nombre_subserie' => 'Fondos Especiales Oficiales', 'id_serie' => 18],
            ['codigo_subserie' => '18.4', 'nombre_subserie' => 'Fondos Especiales Particulares', 'id_serie' => 18],
            ['codigo_subserie' => '18.5', 'nombre_subserie' => 'Fondos Internos', 'id_serie' => 18],
            ['codigo_subserie' => '18.6', 'nombre_subserie' => 'Cuenta Única Nacional', 'id_serie' => 18],
            ['codigo_subserie' => '18.7', 'nombre_subserie' => 'Cuota de Compensación Militar', 'id_serie' => 18],
            ['codigo_subserie' => '18.8', 'nombre_subserie' => 'Depósitos Especiales', 'id_serie' => 18],
            ['codigo_subserie' => '18.9', 'nombre_subserie' => 'Gastos Reservados', 'id_serie' => 18],
            ['codigo_subserie' => '18.10', 'nombre_subserie' => 'Pensiones', 'id_serie' => 18],
            ['codigo_subserie' => '18.11', 'nombre_subserie' => 'Plan Especial', 'id_serie' => 18],
            ['codigo_subserie' => '18.12', 'nombre_subserie' => 'Fondo de Defensa', 'id_serie' => 18],

            ['codigo_subserie' => '19.1', 'nombre_subserie' => 'Cuenta Fiscal de Gastos Reservados', 'id_serie' => 19],
            ['codigo_subserie' => '19.2', 'nombre_subserie' => 'Cuenta Fiscal de Bienes', 'id_serie' => 19],
            ['codigo_subserie' => '19.3', 'nombre_subserie' => 'Cuenta Fiscal Recompensas', 'id_serie' => 19],

            ['codigo_subserie' => '20.1', 'nombre_subserie' => 'Declaraciones de Exportación', 'id_serie' => 20],
            ['codigo_subserie' => '20.2', 'nombre_subserie' => 'Declaraciones de Importación', 'id_serie' => 20],
            ['codigo_subserie' => '20.3', 'nombre_subserie' => 'Acinpro', 'id_serie' => 20],
            ['codigo_subserie' => '20.4', 'nombre_subserie' => 'Ministerio de Comunicaciones', 'id_serie' => 20],
            ['codigo_subserie' => '20.5', 'nombre_subserie' => 'Sayco', 'id_serie' => 20],


            ['codigo_subserie' => '21.1', 'nombre_subserie' => 'Canónicos', 'id_serie' => 21],

            ['codigo_subserie' => '23.1', 'nombre_subserie' => 'Canónicos', 'id_serie' => 21],

            ['codigo_subserie' => '23.1', 'nombre_subserie' => 'Directiva Permanente', 'id_serie' => 23],
            ['codigo_subserie' => '23.2', 'nombre_subserie' => 'Directiva Transitoria', 'id_serie' => 23],

            ['codigo_subserie' => '24.2', 'nombre_subserie' => 'Estudio Análisis de o para Curso', 'id_serie' => 24],
            ['codigo_subserie' => '24.3', 'nombre_subserie' => 'Estudio Criminológico', 'id_serie' => 24],
            ['codigo_subserie' => '24.4', 'nombre_subserie' => 'Estudio Comisión Sinai', 'id_serie' => 24],
            ['codigo_subserie' => '24.5', 'nombre_subserie' => 'Estudio Seguridad a Personas', 'id_serie' => 24],
            ['codigo_subserie' => '24.6', 'nombre_subserie' => 'Estudio Seguridad a Unidades', 'id_serie' => 24],
            ['codigo_subserie' => '24.7', 'nombre_subserie' => 'Estudio de Área', 'id_serie' => 24],
            ['codigo_subserie' => '24.8', 'nombre_subserie' => 'Estudio de Cooperantes', 'id_serie' => 24],
            ['codigo_subserie' => '24.9', 'nombre_subserie' => 'Estudio de Costos', 'id_serie' => 24],
            ['codigo_subserie' => '24.10', 'nombre_subserie' => 'Estudio de Desmovilizados', 'id_serie' => 24],
            ['codigo_subserie' => '24.11', 'nombre_subserie' => 'Estudio de Estandarización', 'id_serie' => 24],
            ['codigo_subserie' => '24.12', 'nombre_subserie' => 'Estudio de Mercado', 'id_serie' => 24],
            ['codigo_subserie' => '24.13', 'nombre_subserie' => 'Estudio de Planeación', 'id_serie' => 24],
            ['codigo_subserie' => '24.14', 'nombre_subserie' => 'Estudio de Politica Exterior', 'id_serie' => 24],
            ['codigo_subserie' => '24.15', 'nombre_subserie' => 'Estudio de Redes de Comunicación', 'id_serie' => 24],
            ['codigo_subserie' => '24.16', 'nombre_subserie' => 'Estudio de Seguridad a Vias', 'id_serie' => 24],
            ['codigo_subserie' => '24.17', 'nombre_subserie' => 'Estudio de Seguridad de Documentos', 'id_serie' => 24],
            ['codigo_subserie' => '24.18', 'nombre_subserie' => 'Estudio de Suelos', 'id_serie' => 24],
            ['codigo_subserie' => '24.19', 'nombre_subserie' => 'Estudio Investigación Secuestro y Extorsión', 'id_serie' => 24],
            ['codigo_subserie' => '24.20', 'nombre_subserie' => 'Estudio Técnico de Automotores', 'id_serie' => 24],

            ['codigo_subserie' => '25.1', 'nombre_subserie' => 'Expediente de Equipos', 'id_serie' => 25],
            ['codigo_subserie' => '25.2', 'nombre_subserie' => 'Expediente de Vehículos', 'id_serie' => 25],
            ['codigo_subserie' => '25.2', 'nombre_subserie' => 'Expediente de Vehículos', 'id_serie' => 25],
            ['codigo_subserie' => '25.3', 'nombre_subserie' => 'Expediente de Actividad Académica', 'id_serie' => 25],
            ['codigo_subserie' => '25.4', 'nombre_subserie' => 'Expediente de Admisión de Alumnos', 'id_serie' => 25],
            ['codigo_subserie' => '25.5', 'nombre_subserie' => 'Expediente de Alcocensores', 'id_serie' => 25],
            ['codigo_subserie' => '25.6', 'nombre_subserie' => 'Expediente de Armamento', 'id_serie' => 25],
            ['codigo_subserie' => '25.7', 'nombre_subserie' => 'Expediente de Armamento Decomizado o Incautado', 'id_serie' => 25],
            ['codigo_subserie' => '25.8', 'nombre_subserie' => 'Expediente de Buques', 'id_serie' => 25],
            ['codigo_subserie' => '25.9', 'nombre_subserie' => 'Expediente de Cultivos Ilicitos', 'id_serie' => 25],
            ['codigo_subserie' => '25.10', 'nombre_subserie' => 'Expediente de Delitos', 'id_serie' => 25],
            ['codigo_subserie' => '25.11', 'nombre_subserie' => 'Expediente de Derechos Humanos', 'id_serie' => 25],
            ['codigo_subserie' => '25.12', 'nombre_subserie' => 'Expediente de Desaparecido', 'id_serie' => 25],
            ['codigo_subserie' => '25.13', 'nombre_subserie' => 'Expediente de Desmovilizados', 'id_serie' => 25],
            ['codigo_subserie' => '25.14', 'nombre_subserie' => 'Expediente de Detenido', 'id_serie' => 25],
            ['codigo_subserie' => '25.15', 'nombre_subserie' => 'Expediente de Inteligencia', 'id_serie' => 25],
            ['codigo_subserie' => '25.16', 'nombre_subserie' => 'Expediente de Leishmaniasis', 'id_serie' => 25],
            ['codigo_subserie' => '25.17', 'nombre_subserie' => 'Expediente de Liberado', 'id_serie' => 25],
            ['codigo_subserie' => '25.18', 'nombre_subserie' => 'Expediente de Nacionalización', 'id_serie' => 25],
            ['codigo_subserie' => '25.19', 'nombre_subserie' => 'Expediente de Paciente Epidemiológico', 'id_serie' => 25],
            ['codigo_subserie' => '25.20', 'nombre_subserie' => 'Expediente de Pagos Recompensas', 'id_serie' => 25],
            ['codigo_subserie' => '25.21', 'nombre_subserie' => 'Expediente de Secuestrado', 'id_serie' => 25],
            ['codigo_subserie' => '25.22', 'nombre_subserie' => 'Expediente de Semovientes', 'id_serie' => 25],
            ['codigo_subserie' => '25.23', 'nombre_subserie' => 'Expediente de Servicio', 'id_serie' => 25],
            ['codigo_subserie' => '25.24', 'nombre_subserie' => 'Expediente Especial de Contrainteligencia', 'id_serie' => 25],
            ['codigo_subserie' => '25.25', 'nombre_subserie' => 'Expediente Especial de Personas', 'id_serie' => 25],

            ['codigo_subserie' => '26.1', 'nombre_subserie' => 'Control Gastos Generales', 'id_serie' => 26],
            ['codigo_subserie' => '26.2', 'nombre_subserie' => 'Comprobantes de Pago / Gastos Personal', 'id_serie' => 26],

            ['codigo_subserie' => '27.1', 'nombre_subserie' => 'Anticipo de Cesantias', 'id_serie' => 27],
            ['codigo_subserie' => '27.2', 'nombre_subserie' => 'Asuntos Disciplinarios', 'id_serie' => 27],
            ['codigo_subserie' => '27.3', 'nombre_subserie' => 'Asuntos Juridicos', 'id_serie' => 27],
            ['codigo_subserie' => '27.4', 'nombre_subserie' => 'Asuntos Médicos', 'id_serie' => 27],
            ['codigo_subserie' => '27.5', 'nombre_subserie' => 'Cesantia Definitiva', 'id_serie' => 27],
            ['codigo_subserie' => '27.6', 'nombre_subserie' => 'Hoja de Vida', 'id_serie' => 27],
            ['codigo_subserie' => '27.7', 'nombre_subserie' => 'Pensión de Invalidéz', 'id_serie' => 27],
            ['codigo_subserie' => '27.8', 'nombre_subserie' => 'Pensión de Jubilación', 'id_serie' => 27],
            ['codigo_subserie' => '27.9', 'nombre_subserie' => 'Pensión de Sobrevivientes', 'id_serie' => 27],
            ['codigo_subserie' => '27.10', 'nombre_subserie' => 'Sustitución Pensional', 'id_serie' => 27],
            ['codigo_subserie' => '27.11', 'nombre_subserie' => 'Pensión por muerte', 'id_serie' => 27],
            ['codigo_subserie' => '27.12', 'nombre_subserie' => 'Pedimento Vario', 'id_serie' => 27],
            ['codigo_subserie' => '27.13', 'nombre_subserie' => 'Veterano Corea, o Perú', 'id_serie' => 27],

            ['codigo_subserie' => '28.1', 'nombre_subserie' => 'Comunicados de Prensa', 'id_serie' => 28],
            ['codigo_subserie' => '28.2', 'nombre_subserie' => 'Discursos', 'id_serie' => 28],
            ['codigo_subserie' => '28.3', 'nombre_subserie' => 'Pronunciamientos', 'id_serie' => 28],
            ['codigo_subserie' => '28.4', 'nombre_subserie' => 'Guiones', 'id_serie' => 28],
            ['codigo_subserie' => '28.5', 'nombre_subserie' => 'Evaluacion de Prensa', 'id_serie' => 28],
            ['codigo_subserie' => '28.6', 'nombre_subserie' => 'Programación Salida Insignia', 'id_serie' => 28],
            ['codigo_subserie' => '28.7', 'nombre_subserie' => 'Evaluación de Gestion', 'id_serie' => 28],

            ['codigo_subserie' => '29.1', 'nombre_subserie' => 'Informe a Entes de Control', 'id_serie' => 29],
            ['codigo_subserie' => '29.2', 'nombre_subserie' => 'Informe Contable', 'id_serie' => 29],
            ['codigo_subserie' => '29.3', 'nombre_subserie' => 'Informe de Auditoria', 'id_serie' => 29],
            ['codigo_subserie' => '29.4', 'nombre_subserie' => 'Informe de Austeridad en el Gasto Público', 'id_serie' => 29],
            ['codigo_subserie' => '29.5', 'nombre_subserie' => 'Informe de Avance del Plan de Acción', 'id_serie' => 29],
            ['codigo_subserie' => '29.6', 'nombre_subserie' => 'Informe de Ejecución Presupuestal', 'id_serie' => 29],
            ['codigo_subserie' => '29.7', 'nombre_subserie' => 'Informe de Estados Financieros', 'id_serie' => 29],
            ['codigo_subserie' => '29.8', 'nombre_subserie' => 'Informe de Extorsión o Secuestro', 'id_serie' => 29],
            ['codigo_subserie' => '29.9', 'nombre_subserie' => 'Informe de Memorias al Congreso', 'id_serie' => 29],
            ['codigo_subserie' => '29.10', 'nombre_subserie' => 'Informe de Seguimiento y Evaluación', 'id_serie' => 29],
            ['codigo_subserie' => '29.11', 'nombre_subserie' => 'Informe Ejecutivo', 'id_serie' => 29],
            ['codigo_subserie' => '29.12', 'nombre_subserie' => 'Informe Estadistico', 'id_serie' => 29],
            ['codigo_subserie' => '29.13', 'nombre_subserie' => 'Informe Material Perdido o Dañado', 'id_serie' => 29],
            ['codigo_subserie' => '29.14', 'nombre_subserie' => 'Informe Administrativo', 'id_serie' => 29],
            ['codigo_subserie' => '29.15', 'nombre_subserie' => 'Informe Estado Diario Plantas Equipo', 'id_serie' => 29],
            ['codigo_subserie' => '29.16', 'nombre_subserie' => 'Informe Analisis Calidad Educativa', 'id_serie' => 29],
            ['codigo_subserie' => '29.17', 'nombre_subserie' => 'Informe Anual Análisis Psicológico', 'id_serie' => 29],
            ['codigo_subserie' => '29.18', 'nombre_subserie' => 'Informe Periódico Base de Datos', 'id_serie' => 29],
            ['codigo_subserie' => '29.19', 'nombre_subserie' => 'Informe de Back-Up', 'id_serie' => 29],
            ['codigo_subserie' => '29.20', 'nombre_subserie' => 'Informe de Bienes Decomisados Provisionalmente por el DNE', 'id_serie' => 29],
            ['codigo_subserie' => '29.21', 'nombre_subserie' => 'Informe de Inspección o Revista', 'id_serie' => 29],
            ['codigo_subserie' => '29.22', 'nombre_subserie' => 'Informe de Incautación Sustancias Alucinógenas', 'id_serie' => 29],
            ['codigo_subserie' => '29.23', 'nombre_subserie' => 'Informe Técnico', 'id_serie' => 29],
            ['codigo_subserie' => '29.24', 'nombre_subserie' => 'Informe de Apreciación', 'id_serie' => 29],
            ['codigo_subserie' => '29.25', 'nombre_subserie' => 'Informe de Actividades', 'id_serie' => 29],
            ['codigo_subserie' => '29.26', 'nombre_subserie' => 'Informe de Armamento.', 'id_serie' => 29],
            ['codigo_subserie' => '29.27', 'nombre_subserie' => 'Informe de Gestion', 'id_serie' => 29],
            ['codigo_subserie' => '29.28', 'nombre_subserie' => 'Informe Sistema de Control Interno', 'id_serie' => 29],
            ['codigo_subserie' => '29.29', 'nombre_subserie' => 'Informe de Accidentalidad', 'id_serie' => 29],
            ['codigo_subserie' => '29.30', 'nombre_subserie' => 'Informe Periódico Acciones Psicologicas', 'id_serie' => 29],
            ['codigo_subserie' => '29.31', 'nombre_subserie' => 'Informe Prueba alumnos', 'id_serie' => 29],
            ['codigo_subserie' => '29.32', 'nombre_subserie' => 'Informe Análisis de Mercado', 'id_serie' => 29],
            ['codigo_subserie' => '29.33', 'nombre_subserie' => 'Informe Anticorrupción', 'id_serie' => 29],
            ['codigo_subserie' => '29.34', 'nombre_subserie' => 'Informe Apreciación de Situación', 'id_serie' => 29],
            ['codigo_subserie' => '29.36', 'nombre_subserie' => 'Informe Centro Nacional de Afiliación - CENAF', 'id_serie' => 29],
            ['codigo_subserie' => '29.37', 'nombre_subserie' => 'Informe Comisión Legal de Cuentas', 'id_serie' => 29],
            ['codigo_subserie' => '29.38', 'nombre_subserie' => 'Informe Constitución LOAS', 'id_serie' => 29],
            ['codigo_subserie' => '29.39', 'nombre_subserie' => 'Informe Control de Producción', 'id_serie' => 29],
            ['codigo_subserie' => '29.40', 'nombre_subserie' => 'Informe de Ascenso', 'id_serie' => 29],
            ['codigo_subserie' => '29.41', 'nombre_subserie' => 'Informe de Autopsia Psicológica', 'id_serie' => 29],
            ['codigo_subserie' => '29.42', 'nombre_subserie' => 'Informe de Capacitación', 'id_serie' => 29],
            ['codigo_subserie' => '29.43', 'nombre_subserie' => 'Informe de Contrainteligencia', 'id_serie' => 29],
            ['codigo_subserie' => '29.44', 'nombre_subserie' => 'Informe de Control de Calidad', 'id_serie' => 29],
            ['codigo_subserie' => '29.45', 'nombre_subserie' => 'Informe de Control de Medios Logisticos', 'id_serie' => 29],
            ['codigo_subserie' => '29.46', 'nombre_subserie' => 'Informe de Coordinación de Grupos', 'id_serie' => 29],
            ['codigo_subserie' => '29.47', 'nombre_subserie' => 'Informe de Costos', 'id_serie' => 29],
            ['codigo_subserie' => '29.48', 'nombre_subserie' => 'Informe de Delitos Politicos', 'id_serie' => 29],
            ['codigo_subserie' => '29.49', 'nombre_subserie' => 'Informe de Entrevistas', 'id_serie' => 29],
            ['codigo_subserie' => '29.50', 'nombre_subserie' => 'Informe de Fondos', 'id_serie' => 29],
            ['codigo_subserie' => '29.51', 'nombre_subserie' => 'Informe de Incorporación', 'id_serie' => 29],
            ['codigo_subserie' => '29.53', 'nombre_subserie' => 'Informe de Inversiones Financieras', 'id_serie' => 29],
            ['codigo_subserie' => '29.54', 'nombre_subserie' => 'Informe de Investigaciones', 'id_serie' => 29],
            ['codigo_subserie' => '29.55', 'nombre_subserie' => 'Informe de Judialización', 'id_serie' => 29],
            ['codigo_subserie' => '29.56', 'nombre_subserie' => 'Informe de Misiones Agregados Militares', 'id_serie' => 29],
            ['codigo_subserie' => '29.57', 'nombre_subserie' => 'Informe de Novedades', 'id_serie' => 29],
            ['codigo_subserie' => '29.58', 'nombre_subserie' => 'Informe de Operatividad', 'id_serie' => 29],
            ['codigo_subserie' => '29.59', 'nombre_subserie' => 'Informe de Patrullajes', 'id_serie' => 29],
            ['codigo_subserie' => '29.60', 'nombre_subserie' => 'Informe de Personal', 'id_serie' => 29],
            ['codigo_subserie' => '29.61', 'nombre_subserie' => 'Informe de Procesos', 'id_serie' => 29],
            ['codigo_subserie' => '29.62', 'nombre_subserie' => 'Informe de Prueba de Vulnerabilidad', 'id_serie' => 29],
            ['codigo_subserie' => '29.63', 'nombre_subserie' => 'Informe de Prueba de Lealtad', 'id_serie' => 29],
            ['codigo_subserie' => '29.64', 'nombre_subserie' => 'Informe de Puestos de Control', 'id_serie' => 29],
            ['codigo_subserie' => '29.65', 'nombre_subserie' => 'Informe de Resultado', 'id_serie' => 29],
            ['codigo_subserie' => '29.66', 'nombre_subserie' => 'Informe de Riesgo de Operación', 'id_serie' => 29],
            ['codigo_subserie' => '29.67', 'nombre_subserie' => 'Informe de Riesgo Industrial', 'id_serie' => 29],
            ['codigo_subserie' => '29.68', 'nombre_subserie' => 'Informe de Riesgo y Alerta Temprana', 'id_serie' => 29],
            ['codigo_subserie' => '29.69', 'nombre_subserie' => 'Informe de Sistemas de Comunicaciones', 'id_serie' => 29],
            ['codigo_subserie' => '29.70', 'nombre_subserie' => 'Informe de Situación Operacional - INSITOP', 'id_serie' => 29],
            ['codigo_subserie' => '29.71', 'nombre_subserie' => 'Informe de Situacion Orden Público', 'id_serie' => 29],
            ['codigo_subserie' => '29.72', 'nombre_subserie' => 'Informe de Traslados Internos', 'id_serie' => 29],
            ['codigo_subserie' => '29.73', 'nombre_subserie' => 'Informe de Vehiculos', 'id_serie' => 29],
            ['codigo_subserie' => '29.74', 'nombre_subserie' => 'Informe Especial', 'id_serie' => 29],
            ['codigo_subserie' => '29.75', 'nombre_subserie' => 'Informe Estratégico', 'id_serie' => 29],
            ['codigo_subserie' => '29.76', 'nombre_subserie' => 'Informe Final de Accidente o Incidente', 'id_serie' => 29],
            ['codigo_subserie' => '29.77', 'nombre_subserie' => 'Informe Fundicion material decomisado', 'id_serie' => 29],
            ['codigo_subserie' => '29.78', 'nombre_subserie' => 'Informe Infografías', 'id_serie' => 29],
            ['codigo_subserie' => '29.79', 'nombre_subserie' => 'Informe Gerencial', 'id_serie' => 29],
            ['codigo_subserie' => '29.80', 'nombre_subserie' => 'Informe Incidentes Fronterizos', 'id_serie' => 29],
            ['codigo_subserie' => '29.81', 'nombre_subserie' => 'Informe Interno', 'id_serie' => 29],
            ['codigo_subserie' => '29.82', 'nombre_subserie' => 'Informe Listado Armamento DCCA', 'id_serie' => 29],
            ['codigo_subserie' => '29.83', 'nombre_subserie' => 'Informe Material Decomisado', 'id_serie' => 29],
            ['codigo_subserie' => '29.84', 'nombre_subserie' => 'Informe Multas DCCA', 'id_serie' => 29],
            ['codigo_subserie' => '29.85', 'nombre_subserie' => 'Informe Organismos Internacionales', 'id_serie' => 29],
            ['codigo_subserie' => '29.86', 'nombre_subserie' => 'Informe para Judicialización', 'id_serie' => 29],
            ['codigo_subserie' => '29.87', 'nombre_subserie' => 'Informe Periódico de Personal', 'id_serie' => 29],
            ['codigo_subserie' => '29.88', 'nombre_subserie' => 'Informe Periódico de Transportes', 'id_serie' => 29],
            ['codigo_subserie' => '29.89', 'nombre_subserie' => 'Informe Potencial Económico', 'id_serie' => 29],
            ['codigo_subserie' => '29.90', 'nombre_subserie' => 'Informe Protocolario', 'id_serie' => 29],
            ['codigo_subserie' => '29.91', 'nombre_subserie' => 'Informe SICOE', 'id_serie' => 29],
            ['codigo_subserie' => '29.92', 'nombre_subserie' => 'Informe Consejos de Seguridad', 'id_serie' => 29],
            ['codigo_subserie' => '29.93', 'nombre_subserie' => 'Informe de Monitoreo de Uso Final MUF', 'id_serie' => 29],
            ['codigo_subserie' => '29.94', 'nombre_subserie' => 'Informe Medio Ambiente', 'id_serie' => 29],
            ['codigo_subserie' => '29.95', 'nombre_subserie' => 'Informe Sistema Información ATP', 'id_serie' => 29],
            ['codigo_subserie' => '29.96', 'nombre_subserie' => 'Informe Sistema Información EQUALS', 'id_serie' => 29],
            ['codigo_subserie' => '29.97', 'nombre_subserie' => 'Informe Sistema Información Logístico - SAP/R3', 'id_serie' => 29],


            ['codigo_subserie' => '30.1', 'nombre_subserie' => 'Inventario de Aplicativos de Software', 'id_serie' => 30],
            ['codigo_subserie' => '30.2', 'nombre_subserie' => 'Inventario de Backups', 'id_serie' => 30],
            ['codigo_subserie' => '30.3', 'nombre_subserie' => 'Inventario Alocensores', 'id_serie' => 30],
            ['codigo_subserie' => '30.4', 'nombre_subserie' => 'Inventario de Bienes en Bodega', 'id_serie' => 30],
            ['codigo_subserie' => '30.5', 'nombre_subserie' => 'Inventario de Documentos de Gestión', 'id_serie' => 30],
            ['codigo_subserie' => '30.6', 'nombre_subserie' => 'Inventario de Finca Raiz', 'id_serie' => 30],
            ['codigo_subserie' => '30.7', 'nombre_subserie' => 'Inventario de Licencias de Funcionamiento', 'id_serie' => 30],
            ['codigo_subserie' => '30.8', 'nombre_subserie' => 'Inventario de Bienes en Depósito', 'id_serie' => 30],
            ['codigo_subserie' => '30.9', 'nombre_subserie' => 'Inventario de Material de Guerra', 'id_serie' => 30],
            ['codigo_subserie' => '30.10', 'nombre_subserie' => 'Inventario General de Documentos', 'id_serie' => 30],
            ['codigo_subserie' => '30.11', 'nombre_subserie' => 'Inventario Material Decomisado', 'id_serie' => 30],
            ['codigo_subserie' => '30.12', 'nombre_subserie' => 'Inventario de Radares', 'id_serie' => 30],
            ['codigo_subserie' => '30.13', 'nombre_subserie' => 'Inventario Fiscal', 'id_serie' => 30],

            ['codigo_subserie' => '31.1', 'nombre_subserie' => 'Libro Contable', 'id_serie' => 31],
            ['codigo_subserie' => '31.2', 'nombre_subserie' => 'Libro Presupuestal', 'id_serie' => 31],
            ['codigo_subserie' => '31.3', 'nombre_subserie' => 'Libro Auxiliar de Cartera', 'id_serie' => 31],
            ['codigo_subserie' => '31.4', 'nombre_subserie' => 'Libro Album Historico', 'id_serie' => 31],
            ['codigo_subserie' => '31.5', 'nombre_subserie' => 'Libro de Bancos', 'id_serie' => 31],
            ['codigo_subserie' => '31.6', 'nombre_subserie' => 'Libro de Control o Minutas', 'id_serie' => 31],
            ['codigo_subserie' => '31.7', 'nombre_subserie' => 'Libro de Presentación de Personal', 'id_serie' => 31],
            ['codigo_subserie' => '31.8', 'nombre_subserie' => 'Libro de Registro', 'id_serie' => 31],
            ['codigo_subserie' => '31.9', 'nombre_subserie' => 'Libro Diario de Contrainteligencia', 'id_serie' => 31],
            ['codigo_subserie' => '31.10', 'nombre_subserie' => 'Libro Diario de Operaciones', 'id_serie' => 31],
            ['codigo_subserie' => '31.11', 'nombre_subserie' => 'Libro Promesa de Reserva', 'id_serie' => 31],
            ['codigo_subserie' => '31.12', 'nombre_subserie' => 'Libro Radicador de Mensajes', 'id_serie' => 31],

            ['codigo_subserie' => '32.1', 'nombre_subserie' => 'Mantenimiento Estructuras Físicas', 'id_serie' => 32],
            ['codigo_subserie' => '32.2', 'nombre_subserie' => 'Mantenimiento Infraestructura Informática', 'id_serie' => 32],
            ['codigo_subserie' => '32.3', 'nombre_subserie' => 'Mantenimiento Maquinaria y Equipos', 'id_serie' => 32],

            ['codigo_subserie' => '33.1', 'nombre_subserie' => 'Manual de Funciones', 'id_serie' => 33],
            ['codigo_subserie' => '33.2', 'nombre_subserie' => 'Manual de Procedimientos', 'id_serie' => 33],
            ['codigo_subserie' => '33.3', 'nombre_subserie' => 'Manual de Sistema de Gestión de Calidad', 'id_serie' => 33],

            ['codigo_subserie' => '34.1', 'nombre_subserie' => 'Análisis de los Campos del Poder', 'id_serie' => 34],
            ['codigo_subserie' => '34.2', 'nombre_subserie' => 'Analisis de Agenda', 'id_serie' => 34],
            ['codigo_subserie' => '34.3', 'nombre_subserie' => 'Levantamiento Leyendas, Conceptos de Dirección Nacional de Planeación (DNP)', 'id_serie' => 34],
            ['codigo_subserie' => '34.4', 'nombre_subserie' => 'Cartas Azules del Comandante del Ejercito', 'id_serie' => 34],

            ['codigo_subserie' => '35.1', 'nombre_subserie' => 'Reportes', 'id_serie' => 35],

            ['codigo_subserie' => '36.1', 'nombre_subserie' => 'Normas Archivisticas', 'id_serie' => 36],
            ['codigo_subserie' => '36.2', 'nombre_subserie' => 'Normas Técnicas Militares Vigentes', 'id_serie' => 36],

            ['codigo_subserie' => '37.1', 'nombre_subserie' => 'Nómina de Pago', 'id_serie' => 37],
            ['codigo_subserie' => '37.2', 'nombre_subserie' => 'Novedades de Nómina', 'id_serie' => 37],
            ['codigo_subserie' => '37.3', 'nombre_subserie' => 'Planilla Pago Docentes', 'id_serie' => 37],
            ['codigo_subserie' => '37.4', 'nombre_subserie' => 'Descuentos Centralizados', 'id_serie' => 37],
            ['codigo_subserie' => '37.5', 'nombre_subserie' => 'Delegaciones de Pago', 'id_serie' => 37],

            ['codigo_subserie' => '38.1', 'nombre_subserie' => 'Orden Interna', 'id_serie' => 38],
            ['codigo_subserie' => '38.2', 'nombre_subserie' => 'Orden Semanal', 'id_serie' => 38],
            ['codigo_subserie' => '38.3', 'nombre_subserie' => 'Orden Administrativa de Personal', 'id_serie' => 38],
            ['codigo_subserie' => '38.4', 'nombre_subserie' => 'Orden de Operación', 'id_serie' => 38],
            ['codigo_subserie' => '38.5', 'nombre_subserie' => 'Orden Administrativa de Partidas Fiscales', 'id_serie' => 38],
            ['codigo_subserie' => '38.6', 'nombre_subserie' => 'Orden General', 'id_serie' => 38],
            ['codigo_subserie' => '38.7', 'nombre_subserie' => 'Orden Administrativa de Presupuesto', 'id_serie' => 38],
            ['codigo_subserie' => '38.8', 'nombre_subserie' => 'Orden Pasajes y Viaticos', 'id_serie' => 38],
            ['codigo_subserie' => '38.9', 'nombre_subserie' => 'Orden Administrativa Servicio Técnico de Transportes', 'id_serie' => 38],
            ['codigo_subserie' => '38.10', 'nombre_subserie' => 'Orden de Cumplimiento', 'id_serie' => 38],
            ['codigo_subserie' => '38.11', 'nombre_subserie' => 'Orden de Entrega de Elementos o Procedimientos Médicos', 'id_serie' => 38],
            ['codigo_subserie' => '38.12', 'nombre_subserie' => 'Orden de Trabajo', 'id_serie' => 38],
            ['codigo_subserie' => '38.13', 'nombre_subserie' => 'Orden Transitoria', 'id_serie' => 38],
            ['codigo_subserie' => '38.14', 'nombre_subserie' => 'Orden del Dia', 'id_serie' => 38],
            ['codigo_subserie' => '38.15', 'nombre_subserie' => 'Sumario de Ordenes permanentes (SOP)', 'id_serie' => 38],

            ['codigo_subserie' => '39.1', 'nombre_subserie' => 'Doctrinas', 'id_serie' => 39],

            ['codigo_subserie' => '40.1', 'nombre_subserie' => 'Plan Anual de Compras', 'id_serie' => 40],
            ['codigo_subserie' => '40.2', 'nombre_subserie' => 'Plan de Acción', 'id_serie' => 40],
            ['codigo_subserie' => '40.3', 'nombre_subserie' => 'Plan de Auditoría', 'id_serie' => 40],
            ['codigo_subserie' => '40.4', 'nombre_subserie' => 'Plan de Capacitación', 'id_serie' => 40],
            ['codigo_subserie' => '40.5', 'nombre_subserie' => 'Plan de Comunicación Institucional', 'id_serie' => 40],
            ['codigo_subserie' => '40.6', 'nombre_subserie' => 'Plan de Mantenimiento', 'id_serie' => 40],
            ['codigo_subserie' => '40.7', 'nombre_subserie' => 'Plan de Mejoramiento Concertado', 'id_serie' => 40],
            ['codigo_subserie' => '40.8', 'nombre_subserie' => 'Plan de Mejoramiento Continuo', 'id_serie' => 40],
            ['codigo_subserie' => '40.9', 'nombre_subserie' => 'Plan Estratégico', 'id_serie' => 40],
            ['codigo_subserie' => '40.10', 'nombre_subserie' => 'Plan Indicativo Sectorial', 'id_serie' => 40],
            ['codigo_subserie' => '40.11', 'nombre_subserie' => 'Plan Pastoral', 'id_serie' => 40],
            ['codigo_subserie' => '40.12', 'nombre_subserie' => 'Plan de Instrucción y capacitación (PIC)', 'id_serie' => 40],
            ['codigo_subserie' => '40.13', 'nombre_subserie' => 'Plan de Seguridad', 'id_serie' => 40],
            ['codigo_subserie' => '40.14', 'nombre_subserie' => 'Plan de Alistamiento', 'id_serie' => 40],
            ['codigo_subserie' => '40.15', 'nombre_subserie' => 'Plan de Campaña', 'id_serie' => 40],
            ['codigo_subserie' => '40.16', 'nombre_subserie' => 'Plan Abastecimiento, PAC', 'id_serie' => 40],
            ['codigo_subserie' => '40.17', 'nombre_subserie' => 'Plan de Construcciones', 'id_serie' => 40],
            ['codigo_subserie' => '40.18', 'nombre_subserie' => 'Plan de Desarrollo Administrativo', 'id_serie' => 40],
            ['codigo_subserie' => '40.19', 'nombre_subserie' => 'Plan de Distribución', 'id_serie' => 40],
            ['codigo_subserie' => '40.20', 'nombre_subserie' => 'Plan de Emergencia', 'id_serie' => 40],
            ['codigo_subserie' => '40.21', 'nombre_subserie' => 'Plan de Instrucción y Entrenamiento (PIE)', 'id_serie' => 40],
            ['codigo_subserie' => '40.22', 'nombre_subserie' => 'Plan de Fondo Interno', 'id_serie' => 40],
            ['codigo_subserie' => '40.23', 'nombre_subserie' => 'Plan de Entrenamiento', 'id_serie' => 40],
            ['codigo_subserie' => '40.24', 'nombre_subserie' => 'Plan de Entrenamiento Técnico', 'id_serie' => 40],
            ['codigo_subserie' => '40.25', 'nombre_subserie' => 'Plan Contrainteligencia', 'id_serie' => 40],
            ['codigo_subserie' => '40.26', 'nombre_subserie' => 'Plan de Búsqueda', 'id_serie' => 40],
            ['codigo_subserie' => '40.27', 'nombre_subserie' => 'Plan de Entrenamiento Vuelos al Exterior', 'id_serie' => 40],
            ['codigo_subserie' => '40.28', 'nombre_subserie' => 'Plan de Proyectos Informaticos', 'id_serie' => 40],
            ['codigo_subserie' => '40.29', 'nombre_subserie' => 'Plan Indicativo Gestion', 'id_serie' => 40],
            ['codigo_subserie' => '40.30', 'nombre_subserie' => 'Plan Supervisión Actividades Academicas', 'id_serie' => 40],
            ['codigo_subserie' => '40.31', 'nombre_subserie' => 'Plan de Bienestar de Personal', 'id_serie' => 40],
            ['codigo_subserie' => '40.32', 'nombre_subserie' => 'Plan de Acción Integral', 'id_serie' => 40],
            ['codigo_subserie' => '40.33', 'nombre_subserie' => 'Plan Operacional', 'id_serie' => 40],
            ['codigo_subserie' => '40.34', 'nombre_subserie' => 'Plan Visita Planteles Educativos', 'id_serie' => 40],
            ['codigo_subserie' => '40.35', 'nombre_subserie' => 'Plan de Formación', 'id_serie' => 40],
            ['codigo_subserie' => '40.36', 'nombre_subserie' => 'Plan de Modernización de Comunicaciones', 'id_serie' => 40],
            ['codigo_subserie' => '40.37', 'nombre_subserie' => 'Plan de Necesidades', 'id_serie' => 40],
            ['codigo_subserie' => '40.38', 'nombre_subserie' => 'Plan de Reclutamiento', 'id_serie' => 40],
            ['codigo_subserie' => '40.39', 'nombre_subserie' => 'Plan de Reacción Ataque y Contraataque', 'id_serie' => 40],
            ['codigo_subserie' => '40.40', 'nombre_subserie' => 'Plan Contra Incendio y siniestro', 'id_serie' => 40],
            ['codigo_subserie' => '40.41', 'nombre_subserie' => 'Plan de Guerra', 'id_serie' => 40],
            ['codigo_subserie' => '40.42', 'nombre_subserie' => 'Plan de Lección', 'id_serie' => 40],
            ['codigo_subserie' => '40.43', 'nombre_subserie' => 'Plan de Pruebas de Vulnerabilidad', 'id_serie' => 40],
            ['codigo_subserie' => '40.44', 'nombre_subserie' => 'Plan de Reposición y Reparación de Automotores', 'id_serie' => 40],
            ['codigo_subserie' => '40.45', 'nombre_subserie' => 'Plan de Traslados', 'id_serie' => 40],
            ['codigo_subserie' => '40.46', 'nombre_subserie' => 'Plan de Vacaciones', 'id_serie' => 40],
            ['codigo_subserie' => '40.48', 'nombre_subserie' => 'Plan para el Fortalecimiento de la IM', 'id_serie' => 40],
            ['codigo_subserie' => '40.49', 'nombre_subserie' => 'Plan Turistico', 'id_serie' => 40],
            ['codigo_subserie' => '40.50', 'nombre_subserie' => 'Planes Viaje al exterior', 'id_serie' => 40],
            ['codigo_subserie' => '40.51', 'nombre_subserie' => 'Plan Maestro de Salud Mental', 'id_serie' => 40],

            ['codigo_subserie' => '41.1', 'nombre_subserie' => 'Proceso Administrativo', 'id_serie' => 41],
            ['codigo_subserie' => '41.2', 'nombre_subserie' => 'Proceso Civil', 'id_serie' => 41],
            ['codigo_subserie' => '41.3', 'nombre_subserie' => 'Proceso Contractual de Crédito Externo', 'id_serie' => 41],
            ['codigo_subserie' => '41.4', 'nombre_subserie' => 'Proceso de Comunicación Organizacional', 'id_serie' => 41],
            ['codigo_subserie' => '41.5', 'nombre_subserie' => 'Proceso de Conciliación', 'id_serie' => 41],
            ['codigo_subserie' => '41.6', 'nombre_subserie' => 'Proceso de Constitucionalidad de Normas', 'id_serie' => 41],
            ['codigo_subserie' => '41.7', 'nombre_subserie' => 'Proceso de Inconstitucionalidad', 'id_serie' => 41],
            ['codigo_subserie' => '41.8', 'nombre_subserie' => 'Proceso Disciplinario', 'id_serie' => 41],
            ['codigo_subserie' => '41.9', 'nombre_subserie' => 'Proceso Ejecutivo por Jurisdicción Coactiva', 'id_serie' => 41],
            ['codigo_subserie' => '41.10', 'nombre_subserie' => 'Proceso Judicial', 'id_serie' => 41],
            ['codigo_subserie' => '41.11', 'nombre_subserie' => 'Proceso Laboral', 'id_serie' => 41],
            ['codigo_subserie' => '41.12', 'nombre_subserie' => 'Proceso Penal', 'id_serie' => 41],
            ['codigo_subserie' => '41.13', 'nombre_subserie' => 'Proceso Policivo', 'id_serie' => 41],
            ['codigo_subserie' => '41.14', 'nombre_subserie' => 'Proceso de Negocios Judiciales', 'id_serie' => 41],
            ['codigo_subserie' => '41.15', 'nombre_subserie' => 'Proceso por Pérdida de Elementos', 'id_serie' => 41],
            ['codigo_subserie' => '41.16', 'nombre_subserie' => 'Proceso de Salud Ocupacional', 'id_serie' => 41],

            ['codigo_subserie' => '43.1', 'nombre_subserie' => 'Proyecto Anual de Presupuesto', 'id_serie' => 43],
            ['codigo_subserie' => '43.2', 'nombre_subserie' => 'Proyecto de Cooperación Internacional', 'id_serie' => 43],
            ['codigo_subserie' => '43.3', 'nombre_subserie' => 'Proyecto de Cooperación Nacional', 'id_serie' => 43],
            ['codigo_subserie' => '43.4', 'nombre_subserie' => 'Proyecto de Libre Inversión', 'id_serie' => 43],
            ['codigo_subserie' => '43.5', 'nombre_subserie' => 'Proyecto de Organización', 'id_serie' => 43],
            ['codigo_subserie' => '43.6', 'nombre_subserie' => 'Proyecto de Politica Internacional Colombiana', 'id_serie' => 43],
            ['codigo_subserie' => '43.7', 'nombre_subserie' => 'Proyecto Integral, Estabilización para las Fuerzas', 'id_serie' => 43],
            ['codigo_subserie' => '43.8', 'nombre_subserie' => 'Proyecto Fondo Bienestar y Recreación', 'id_serie' => 43],
            ['codigo_subserie' => '43.9', 'nombre_subserie' => 'Proyección de Infantes de Marina', 'id_serie' => 43],
            ['codigo_subserie' => '43.10', 'nombre_subserie' => 'Proyección de Plantas de Personal', 'id_serie' => 43],
            ['codigo_subserie' => '43.11', 'nombre_subserie' => 'Proyecto de Adquisición', 'id_serie' => 43],
            ['codigo_subserie' => '43.12', 'nombre_subserie' => 'Proyecto de Auditoria', 'id_serie' => 43],
            ['codigo_subserie' => '43.13', 'nombre_subserie' => 'Proyecto de Comunicaciones', 'id_serie' => 43],
            ['codigo_subserie' => '43.14', 'nombre_subserie' => 'Proyecto de Convenios Bilaterales', 'id_serie' => 43],
            ['codigo_subserie' => '43.15', 'nombre_subserie' => 'Proyecto de Extinción de Dominio', 'id_serie' => 43],
            ['codigo_subserie' => '43.16', 'nombre_subserie' => 'Proyecto de Grado', 'id_serie' => 43],
            ['codigo_subserie' => '43.17', 'nombre_subserie' => 'Proyecto de Inversión', 'id_serie' => 43],
            ['codigo_subserie' => '43.18', 'nombre_subserie' => 'Proyecto de Investigación', 'id_serie' => 43],
            ['codigo_subserie' => '43.19', 'nombre_subserie' => 'Proyecto de Ley', 'id_serie' => 43],

            ['codigo_subserie' => '46.1', 'nombre_subserie' => 'Resolución Ministerial', 'id_serie' => 46],
            ['codigo_subserie' => '46.2', 'nombre_subserie' => 'Resolución Policía Nacional', 'id_serie' => 46],
            ['codigo_subserie' => '46.3', 'nombre_subserie' => 'Resolución Prestacional', 'id_serie' => 46],
            ['codigo_subserie' => '46.4', 'nombre_subserie' => 'Resolución Armada', 'id_serie' => 46],
            ['codigo_subserie' => '46.5', 'nombre_subserie' => 'Resolución Ejército', 'id_serie' => 46],
            ['codigo_subserie' => '46.6', 'nombre_subserie' => 'Resolución Comando General', 'id_serie' => 46],
            ['codigo_subserie' => '46.7', 'nombre_subserie' => 'Resolución Fuerza Aérea', 'id_serie' => 46],

            ['codigo_subserie' => '47.1', 'nombre_subserie' => 'Sistema Integrado de Información Financiera - SIIF', 'id_serie' => 47],
            ['codigo_subserie' => '47.2', 'nombre_subserie' => 'Sistema de Administración de Correspondencia', 'id_serie' => 47],
            ['codigo_subserie' => '47.3', 'nombre_subserie' => 'Sistema de Información y Estadística', 'id_serie' => 47],
            ['codigo_subserie' => '47.4', 'nombre_subserie' => 'Sistema Integrado de Información Logística - SILOG', 'id_serie' => 47],
            ['codigo_subserie' => '47.5', 'nombre_subserie' => 'Sistema de Administración del Talento Humano', 'id_serie' => 47],
            ['codigo_subserie' => '47.6', 'nombre_subserie' => 'Aplicativo Centro de Información Estadistica', 'id_serie' => 47],
            ['codigo_subserie' => '47.7', 'nombre_subserie' => 'Aplicativo Prestaciones Sociales', 'id_serie' => 47],
            ['codigo_subserie' => '47.8', 'nombre_subserie' => 'Aplicativo Resolución 36', 'id_serie' => 47],
            ['codigo_subserie' => '47.9', 'nombre_subserie' => 'Aplicativo SIDEIN', 'id_serie' => 47],
            ['codigo_subserie' => '47.10', 'nombre_subserie' => 'Base de Datos Normas Técnicas', 'id_serie' => 47],
            ['codigo_subserie' => '47.11', 'nombre_subserie' => 'Sistema Integrado de Planeación', 'id_serie' => 47],
            ['codigo_subserie' => '47.12', 'nombre_subserie' => 'Sistema Proyectos de Inversión', 'id_serie' => 47],
            ['codigo_subserie' => '47.13', 'nombre_subserie' => 'Sistema de Confiabilidad Aeronautica', 'id_serie' => 47],
            ['codigo_subserie' => '47.14', 'nombre_subserie' => 'Sistema de Información de Contratación Estatal', 'id_serie' => 47],


            ['codigo_subserie' => '50.1', 'nombre_subserie' => 'Transferencias Primarias', 'id_serie' => 50],
            ['codigo_subserie' => '50.2', 'nombre_subserie' => 'Transferencias Secundarias', 'id_serie' => 50],


            ['codigo_subserie' => '51.1', 'nombre_subserie' => 'Tratados de Limitación Maritima', 'id_serie' => 51],
            ['codigo_subserie' => '51.2', 'nombre_subserie' => 'Tratados Internacionales', 'id_serie' => 51],

            ['codigo_subserie' => '53.1', 'nombre_subserie' => 'Planilla de Actividades Bachilleres', 'id_serie' => 53],
            ['codigo_subserie' => '53.2', 'nombre_subserie' => 'Planilla de Asignación de Siglas', 'id_serie' => 53],
            ['codigo_subserie' => '53.3', 'nombre_subserie' => 'Planilla de Correspondencia (o libro)', 'id_serie' => 53],
            ['codigo_subserie' => '53.4', 'nombre_subserie' => 'Planilla Reporte Repetidoras', 'id_serie' => 53],
            ['codigo_subserie' => '53.5', 'nombre_subserie' => 'Planilla Reporte Tráfico', 'id_serie' => 53],
            ['codigo_subserie' => '53.6', 'nombre_subserie' => 'Planilla Reporte Sistematizado de Radiogramas', 'id_serie' => 53],
            ['codigo_subserie' => '53.7', 'nombre_subserie' => 'Planilla de Control', 'id_serie' => 53],
            ['codigo_subserie' => '53.8', 'nombre_subserie' => 'Planilla de Materia Prima', 'id_serie' => 53],
            ['codigo_subserie' => '53.9', 'nombre_subserie' => 'Planilla de Partes de Personal', 'id_serie' => 53],
            ['codigo_subserie' => '53.10', 'nombre_subserie' => 'Planilla de Recurso Tecnológicos', 'id_serie' => 53],
            ['codigo_subserie' => '53.11', 'nombre_subserie' => 'Planilla de Registro Nevera Biológicos', 'id_serie' => 53],
            ['codigo_subserie' => '53.12', 'nombre_subserie' => 'Planilla de Reporte Seguros', 'id_serie' => 53],
            ['codigo_subserie' => '53.13', 'nombre_subserie' => 'Planilla de ventas', 'id_serie' => 53],

            ['codigo_subserie' => '55.1', 'nombre_subserie' => 'Encuesta de Aplicación de las TRD', 'id_serie' => 55],
            ['codigo_subserie' => '55.2', 'nombre_subserie' => 'Encuesta de Inicio y Término de Curso', 'id_serie' => 55],
            ['codigo_subserie' => '55.3', 'nombre_subserie' => 'Encuesta de Servicios', 'id_serie' => 55],
            ['codigo_subserie' => '55.4', 'nombre_subserie' => 'Encuesta Estudio Unidad Documental', 'id_serie' => 55],

            ['codigo_subserie' => '56.1', 'nombre_subserie' => 'Estadística Personal con Proceso Juridico', 'id_serie' => 56],
            ['codigo_subserie' => '56.2', 'nombre_subserie' => 'Estadistica de Servicios Públicos', 'id_serie' => 56],
            ['codigo_subserie' => '56.3', 'nombre_subserie' => 'Cuadros Estadísticos', 'id_serie' => 56],
            ['codigo_subserie' => '56.4', 'nombre_subserie' => 'Estadistica Operacional', 'id_serie' => 56],
            ['codigo_subserie' => '56.5', 'nombre_subserie' => 'Estadistica Semanal Cursos', 'id_serie' => 56],
            ['codigo_subserie' => '56.6', 'nombre_subserie' => 'Estadistica Criminal', 'id_serie' => 56],
            ['codigo_subserie' => '56.7', 'nombre_subserie' => 'Estadistica de Compromiso Antidrogas', 'id_serie' => 56],
            ['codigo_subserie' => '56.8', 'nombre_subserie' => 'Estadística de Conciliaciones', 'id_serie' => 56],
            ['codigo_subserie' => '56.9', 'nombre_subserie' => 'Estadística de Control Portuario', 'id_serie' => 56],
            ['codigo_subserie' => '56.10', 'nombre_subserie' => 'Estadistica de Cooperación Mutua', 'id_serie' => 56],
            ['codigo_subserie' => '56.11', 'nombre_subserie' => 'Estadistica de Cooperantes', 'id_serie' => 56],
            ['codigo_subserie' => '56.12', 'nombre_subserie' => 'Estadística de Delitos Violación Derechos de Menores', 'id_serie' => 56],
            ['codigo_subserie' => '56.13', 'nombre_subserie' => 'Estadística de Dinámica Delicuencial y Contravencional', 'id_serie' => 56],
            ['codigo_subserie' => '56.14', 'nombre_subserie' => 'Estadistica de Dotación', 'id_serie' => 56],
            ['codigo_subserie' => '56.15', 'nombre_subserie' => 'Estadistica de Enfermedades de Notificación Obligatoris', 'id_serie' => 56],
            ['codigo_subserie' => '56.16', 'nombre_subserie' => 'Estadística de Gestión', 'id_serie' => 56],
            ['codigo_subserie' => '56.17', 'nombre_subserie' => 'Estadística de Procesos Preliminares Justicia Penal Militar', 'id_serie' => 56],
            ['codigo_subserie' => '56.18', 'nombre_subserie' => 'Estadística Red de Servicios', 'id_serie' => 56],

            ['codigo_subserie' => '57.1', 'nombre_subserie' => 'Campaña de Conservación de Sitios y Patrimonios Culturales', 'id_serie' => 57],
            ['codigo_subserie' => '57.2', 'nombre_subserie' => 'Campaña de Instrucción', 'id_serie' => 57],
            ['codigo_subserie' => '57.3', 'nombre_subserie' => 'Campaña de Prevención de Drogas Ilícitas y Violencia', 'id_serie' => 57],
            ['codigo_subserie' => '57.4', 'nombre_subserie' => 'Campaña de Prevención de Secuestro y Extorsión', 'id_serie' => 57],

            ['codigo_subserie' => '59.1', 'nombre_subserie' => 'Comisiones al Exterior', 'id_serie' => 59],
            ['codigo_subserie' => '59.2', 'nombre_subserie' => 'Comisiones al Interior', 'id_serie' => 59],

            ['codigo_subserie' => '60.1', 'nombre_subserie' => 'Convenio de Cooperación', 'id_serie' => 60],
            ['codigo_subserie' => '60.2', 'nombre_subserie' => 'Convenio Educativo', 'id_serie' => 60],
            ['codigo_subserie' => '60.3', 'nombre_subserie' => 'Convenio Externo', 'id_serie' => 60],
            ['codigo_subserie' => '60.4', 'nombre_subserie' => 'Convenio Interinstitucional', 'id_serie' => 60],
            ['codigo_subserie' => '60.5', 'nombre_subserie' => 'Convenio Internacional', 'id_serie' => 60],
            ['codigo_subserie' => '60.6', 'nombre_subserie' => 'Convenio Recreodeportivo', 'id_serie' => 60],
            ['codigo_subserie' => '60.7', 'nombre_subserie' => 'Convenio Multilateral', 'id_serie' => 60],
            ['codigo_subserie' => '60.8', 'nombre_subserie' => 'Convenio Interadministrativo', 'id_serie' => 60],

            ['codigo_subserie' => '61.1', 'nombre_subserie' => 'Contravenciones Establecimientos Públicos', 'id_serie' => 61],

            ['codigo_subserie' => '62.1', 'nombre_subserie' => 'Curso de Altos Estudios Militares', 'id_serie' => 62],
            ['codigo_subserie' => '62.2', 'nombre_subserie' => 'Curso de Ascenso', 'id_serie' => 62],
            ['codigo_subserie' => '62.3', 'nombre_subserie' => 'Curso de Contrainteligencia', 'id_serie' => 62],
            ['codigo_subserie' => '62.4', 'nombre_subserie' => 'Curso de Instrucción', 'id_serie' => 62],
            ['codigo_subserie' => '62.5', 'nombre_subserie' => 'Curso de Inteligencia', 'id_serie' => 62],
            ['codigo_subserie' => '62.6', 'nombre_subserie' => 'Curso de Orientación sobre Defensa Nacional', 'id_serie' => 62],
            ['codigo_subserie' => '62.7', 'nombre_subserie' => 'Curso Integral de Defensa Nacional', 'id_serie' => 62],
            ['codigo_subserie' => '62.8', 'nombre_subserie' => 'Curso de Estado Mayor', 'id_serie' => 62],

            ['codigo_subserie' => '64.1', 'nombre_subserie' => 'Agenda Clasificación Anual', 'id_serie' => 64],
            ['codigo_subserie' => '64.2', 'nombre_subserie' => 'Agenda Clasificación Ascenso', 'id_serie' => 64],
            ['codigo_subserie' => '64.3', 'nombre_subserie' => 'Agendas de Trabajo', 'id_serie' => 64],

            ['codigo_subserie' => '67.1', 'nombre_subserie' => 'Bitácora de Navegación', 'id_serie' => 67],
            ['codigo_subserie' => '67.2', 'nombre_subserie' => 'Bitácora de Vuelo', 'id_serie' => 67],

            ['codigo_subserie' => '70.1', 'nombre_subserie' => 'Criterios Programas de Bienestar Social', 'id_serie' => 70],
            ['codigo_subserie' => '70.2', 'nombre_subserie' => 'Financieros y Administrativos', 'id_serie' => 70],

            ['codigo_subserie' => '72.1', 'nombre_subserie' => 'Apreciación de Comunicaciones', 'id_serie' => 72],
            ['codigo_subserie' => '72.2', 'nombre_subserie' => 'Apreciación de Inteligencia', 'id_serie' => 72],
            ['codigo_subserie' => '72.3', 'nombre_subserie' => 'Apreciación de Situación', 'id_serie' => 72],
            ['codigo_subserie' => '72.4', 'nombre_subserie' => 'Apreciación de Contrainteligencia', 'id_serie' => 72],
            ['codigo_subserie' => '72.5', 'nombre_subserie' => 'Apreciación de Incorporación', 'id_serie' => 72],
            ['codigo_subserie' => '72.6', 'nombre_subserie' => 'Apreciación de las Secciones', 'id_serie' => 72],

            ['codigo_subserie' => '73.1', 'nombre_subserie' => 'Investigaciones Administrativas', 'id_serie' => 73],
            ['codigo_subserie' => '73.2', 'nombre_subserie' => 'Investigaciones de Campo', 'id_serie' => 73],
            ['codigo_subserie' => '73.3', 'nombre_subserie' => 'Investigaciones Judiciales Criminalística', 'id_serie' => 73],
            ['codigo_subserie' => '73.4', 'nombre_subserie' => 'Investigaciones Judiciales Delitos Contra el Patrimonio Económico', 'id_serie' => 73],
            ['codigo_subserie' => '73.5', 'nombre_subserie' => 'Investigaciones Judiciales Delitos Contra la vida e Integridad Personal', 'id_serie' => 73],
            ['codigo_subserie' => '73.6', 'nombre_subserie' => 'Investigaciones Judiciales Delitos Especiales', 'id_serie' => 73],
            ['codigo_subserie' => '73.7', 'nombre_subserie' => 'Investigaciones Judiciales Delitos Red Vial Nacional', 'id_serie' => 73],
            ['codigo_subserie' => '73.8', 'nombre_subserie' => 'Investigaciones Judiciales Secuestro y Extorsión', 'id_serie' => 73],

            ['codigo_subserie' => '76.1', 'nombre_subserie' => 'Dictamen Perecial', 'id_serie' => 76],

            ['codigo_subserie' => '77.1', 'nombre_subserie' => 'Ensayos Maestría', 'id_serie' => 77],
            ['codigo_subserie' => '77.2', 'nombre_subserie' => 'Ensayos CAEM', 'id_serie' => 77],
            ['codigo_subserie' => '77.3', 'nombre_subserie' => 'Ensayos Agregados Militares', 'id_serie' => 77],
            ['codigo_subserie' => '77.4', 'nombre_subserie' => 'Practicas Geoestrategicas Nacionales', 'id_serie' => 77],
            ['codigo_subserie' => '77.5', 'nombre_subserie' => 'Practicas Geoestrategicas Internacionales', 'id_serie' => 77],

            ['codigo_subserie' => '80.1', 'nombre_subserie' => 'Mapas de Riesgo', 'id_serie' => 80],
            ['codigo_subserie' => '80.2', 'nombre_subserie' => 'Planes de Mitigación', 'id_serie' => 80],
            ['codigo_subserie' => '80.3', 'nombre_subserie' => 'Sistema de Gestión de Calidad', 'id_serie' => 80],

            ['codigo_subserie' => '81.1', 'nombre_subserie' => 'Operación Aérea', 'id_serie' => 81],
            ['codigo_subserie' => '81.2', 'nombre_subserie' => 'Operación de Contrainteligencia', 'id_serie' => 81],
            ['codigo_subserie' => '81.3', 'nombre_subserie' => 'Operación de Inteligencia', 'id_serie' => 81],
            ['codigo_subserie' => '81.4', 'nombre_subserie' => 'Operación Naval', 'id_serie' => 81],
            ['codigo_subserie' => '81.5', 'nombre_subserie' => 'Operación Terrestre', 'id_serie' => 81],

            ['codigo_subserie' => '83.1', 'nombre_subserie' => 'Planos Arquitectónicos', 'id_serie' => 83],
            ['codigo_subserie' => '83.2', 'nombre_subserie' => 'Planos Eléctricos', 'id_serie' => 83],
            ['codigo_subserie' => '83.3', 'nombre_subserie' => 'Planos Hidráulicos', 'id_serie' => 83],
            ['codigo_subserie' => '83.4', 'nombre_subserie' => 'Planos Record', 'id_serie' => 83],
            ['codigo_subserie' => '83.5', 'nombre_subserie' => 'Planos Sanitarios', 'id_serie' => 83],
            ['codigo_subserie' => '83.6', 'nombre_subserie' => 'Planos Topográficos', 'id_serie' => 83],

            ['codigo_subserie' => '84.1', 'nombre_subserie' => 'Politica Archivística', 'id_serie' => 84],
            ['codigo_subserie' => '84.2', 'nombre_subserie' => 'Politica Criminal', 'id_serie' => 84],
            ['codigo_subserie' => '84.3', 'nombre_subserie' => 'Política de Administración de Personal', 'id_serie' => 84],
            ['codigo_subserie' => '84.4', 'nombre_subserie' => 'Política de Mejoramiento de calidad de Vida', 'id_serie' => 84],
            ['codigo_subserie' => '84.5', 'nombre_subserie' => 'Politica de Servicio Militar', 'id_serie' => 84],
            ['codigo_subserie' => '84.6', 'nombre_subserie' => 'Politica de Servicio Tecnológico', 'id_serie' => 84],
            ['codigo_subserie' => '84.7', 'nombre_subserie' => 'Politica Operacional', 'id_serie' => 84],
            ['codigo_subserie' => '84.8', 'nombre_subserie' => 'Política y Lineas de Investigación', 'id_serie' => 84],

            ['codigo_subserie' => '86.1', 'nombre_subserie' => 'Acreditación de Programas', 'id_serie' => 86],
            ['codigo_subserie' => '86.2', 'nombre_subserie' => 'Programa Académico', 'id_serie' => 86],
            ['codigo_subserie' => '86.3', 'nombre_subserie' => 'Programa Anual de Caja', 'id_serie' => 86],
            ['codigo_subserie' => '86.4', 'nombre_subserie' => 'Programa de Educación Especial', 'id_serie' => 86],
            ['codigo_subserie' => '86.5', 'nombre_subserie' => 'Programa de Erradicación', 'id_serie' => 86],
            ['codigo_subserie' => '86.6', 'nombre_subserie' => 'Programa de Extensión', 'id_serie' => 86],
            ['codigo_subserie' => '86.7', 'nombre_subserie' => 'Programa de Gestión Documental', 'id_serie' => 86],
            ['codigo_subserie' => '86.8', 'nombre_subserie' => 'Programa de Higiene y Seguridad Ocupacional', 'id_serie' => 86],
            ['codigo_subserie' => '86.9', 'nombre_subserie' => 'Programa de Medicina Preventiva y del Trabajo', 'id_serie' => 86],
            ['codigo_subserie' => '86.10', 'nombre_subserie' => 'Programa de Prevención', 'id_serie' => 86],
            ['codigo_subserie' => '86.11', 'nombre_subserie' => 'Programa de Promoción', 'id_serie' => 86],
            ['codigo_subserie' => '86.12', 'nombre_subserie' => 'Programa de Protección', 'id_serie' => 86],
            ['codigo_subserie' => '86.13', 'nombre_subserie' => 'Programa de Salud', 'id_serie' => 86],
            ['codigo_subserie' => '86.14', 'nombre_subserie' => 'Programa de Seguridad', 'id_serie' => 86],
            ['codigo_subserie' => '86.15', 'nombre_subserie' => 'Programa de Selección Servicio Social Obligatorio', 'id_serie' => 86],
            ['codigo_subserie' => '86.16', 'nombre_subserie' => 'Programa General de Compras', 'id_serie' => 86],
            ['codigo_subserie' => '86.17', 'nombre_subserie' => 'Programa Liberados y Secuestrados', 'id_serie' => 86],
            ['codigo_subserie' => '86.18', 'nombre_subserie' => 'Programación Unidades Asesoras', 'id_serie' => 86],

            ['codigo_subserie' => '90.1', 'nombre_subserie' => 'Reporte de Accidentalidad', 'id_serie' => 90],
            ['codigo_subserie' => '90.2', 'nombre_subserie' => 'Reporte de Novedades de Conmutador', 'id_serie' => 90],
            ['codigo_subserie' => '90.3', 'nombre_subserie' => 'Reporte de Seguridad Social Personal NO uniformado', 'id_serie' => 90],

            ['codigo_subserie' => '91.1', 'nombre_subserie' => 'Distritales', 'id_serie' => 91],
            ['codigo_subserie' => '91.2', 'nombre_subserie' => 'Nacionales', 'id_serie' => 91],


            /************************ SUBSERIES ACTUALES ********************************************/
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Acción de Cumplimiento', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Acción de Nulidad y Restablecimiento del Derecho', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Acción de Reparación', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Acción de Reparación Directa', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Acción de Tutela', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Acción Popular', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Derechos de Peticion', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Habeas Corpus', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Habeas Data', 'id_serie' => 92],
            ['codigo_subserie' => '1', 'nombre_subserie' => 'Requerimientos de Justicia', 'id_serie' => 92],

            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas Asignacion', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas Compromiso', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas Conciliación Saldos Cuentas Holding Account', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Capacitación', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Entrega', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Grado', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Eliminación Documental', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Informe de Gestión', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Investigación y Desarrollo', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Posesión', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Reserva', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Reuniones de Trabajo', 'id_serie' => 93],
            ['codigo_subserie' => '2', 'nombre_subserie' => 'Actas de Revista', 'id_serie' => 93],

            ['codigo_subserie' => '3', 'nombre_subserie' => 'Acuerdos', 'id_serie' => 94],
            ['codigo_subserie' => '3', 'nombre_subserie' => 'Acuerdo de cooperacion Internacional', 'id_serie' => 94],
            ['codigo_subserie' => '3', 'nombre_subserie' => 'Acuerdo de cooperacion Nacional', 'id_serie' => 94],

            ['codigo_subserie' => '5', 'nombre_subserie' => 'Administracion Capellanias', 'id_serie' => 95],

            ['codigo_subserie' => '6', 'nombre_subserie' => 'Administracion del Fondo de Defensa Nacional', 'id_serie' => 96],

            ['codigo_subserie' => '8', 'nombre_subserie' => 'Proyecto de Inversión Nacional', 'id_serie' => 97],
            ['codigo_subserie' => '8', 'nombre_subserie' => 'Anteproyecto', 'id_serie' => 97],
            ['codigo_subserie' => '8', 'nombre_subserie' => 'Marco de Gasto Mediano Plazo', 'id_serie' => 97],
            ['codigo_subserie' => '8', 'nombre_subserie' => 'Proyectos de Funcionamiento', 'id_serie' => 97],

            ['codigo_subserie' => '9', 'nombre_subserie' => 'Bienes Raices', 'id_serie' => 98],

            ['codigo_subserie' => '10', 'nombre_subserie' => 'Boletines', 'id_serie' => 99],

            ['codigo_subserie' => '11', 'nombre_subserie' => 'Caja Menor', 'id_serie' => 100],

            ['codigo_subserie' => '12', 'nombre_subserie' => 'Certificados', 'id_serie' => 101],
            ['codigo_subserie' => '12', 'nombre_subserie' => 'Certificado de Bono Pensional', 'id_serie' => 101],
            ['codigo_subserie' => '12', 'nombre_subserie' => 'Certificado de Cancelación Matrícula', 'id_serie' => 101],
            ['codigo_subserie' => '12', 'nombre_subserie' => 'Certificado de Derechos Humanos', 'id_serie' => 101],
            ['codigo_subserie' => '12', 'nombre_subserie' => 'Certificado de Prestación de Servicios', 'id_serie' => 101],

            ['codigo_subserie' => '13', 'nombre_subserie' => 'Circulares', 'id_serie' => 102],

            ['codigo_subserie' => '15', 'nombre_subserie' => 'Conceptos Juridicos', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto Administrativo', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto Contable', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto de Defensa Institucional', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto de Derechos Humanos', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto de Inteligencia o Contrainteligencia', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto de Planeación', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto de Política Exterior', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto Financiero', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto Presupuestal', 'id_serie' => 103],
            ['codigo_subserie' => '15', 'nombre_subserie' => 'Concepto Técnico', 'id_serie' => 103],

            ['codigo_subserie' => '16', 'nombre_subserie' => 'Concursos', 'id_serie' => 104],

            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Arrendamiento', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Bienes o Servicios', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Comodato', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Compraventa', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Consultoría', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Enajenación y Tenencia', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Obra', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato de Prestación de Servicios', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato Interadministrativo', 'id_serie' => 105],
            ['codigo_subserie' => '17', 'nombre_subserie' => 'Contrato trabajador Oficial', 'id_serie' => 105],

            ['codigo_subserie' => '18', 'nombre_subserie' => 'Acreedores Varios', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Cuenta Única Nacional', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Cuota de Compensación Militar', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Depósitos Especiales', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Dineros sujetos a devolución', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Fondo de Defensa', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Fondos Especiales Oficiales', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Fondos Especiales Particulares', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Fondos Internos', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Gastos Generales', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Gastos de Personal', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Gastos Reservados', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Pensiones', 'id_serie' => 106],
            ['codigo_subserie' => '18', 'nombre_subserie' => 'Plan Especial', 'id_serie' => 106],

            ['codigo_subserie' => '19', 'nombre_subserie' => 'Cuenta Fiscal de Gastos Reservados', 'id_serie' => 107],
            ['codigo_subserie' => '19', 'nombre_subserie' => 'Cuenta Fiscal Recompensas', 'id_serie' => 107],
            ['codigo_subserie' => '19', 'nombre_subserie' => 'Cuenta Fiscal de Bienes', 'id_serie' => 107],

            ['codigo_subserie' => '20', 'nombre_subserie' => 'Declaraciones de Exportación', 'id_serie' => 108],
            ['codigo_subserie' => '20', 'nombre_subserie' => 'Acinpro', 'id_serie' => 108],
            ['codigo_subserie' => '20', 'nombre_subserie' => 'Declaraciones de Importación', 'id_serie' => 108],
            ['codigo_subserie' => '20', 'nombre_subserie' => 'Ministerio de Comunicaciones', 'id_serie' => 108],
            ['codigo_subserie' => '20', 'nombre_subserie' => 'Sayco', 'id_serie' => 108],

            ['codigo_subserie' => '21', 'nombre_subserie' => 'Canonicos', 'id_serie' => 109],
            ['codigo_subserie' => '21', 'nombre_subserie' => 'Modificación y Reposición Sacramentos', 'id_serie' => 109],

            ['codigo_subserie' => '23', 'nombre_subserie' => 'Directiva Permanente', 'id_serie' => 110],
            ['codigo_subserie' => '23', 'nombre_subserie' => 'Directiva Transitoria', 'id_serie' => 110],

            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudios', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio Criminológico', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Área', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Cooperantes', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Costos', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Desmovilizados', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio estrategico de bienestar', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Estandarización', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Gestión Ambiental', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Planeación', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Política Exterior', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Redes de Comunicación', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Seguridad a Vías', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Seguridad de Documentos', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio de Suelos', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio Investigación Secuestro y Extorsión', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio Seguridad  a Personas', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio Seguridad a Unidades', 'id_serie' => 111],
            ['codigo_subserie' => '24', 'nombre_subserie' => 'Estudio Técnico de Automotores', 'id_serie' => 111],


        ]);
    }
}
